### ISSUE TITLE
Create Mathworks MATLAB bindings

### ISSUE THREAD

**Issue by boskar** [openslide/openslide#116]
Matlab is one of the most widely used science/engineering enviroment, which supports using external libraries and has some support for creating support for unsupported natively images. 

It should be fairy easy, considering this: 
http://www.mathworks.com/help/matlab/ref/loadlibrary.html

and especially this:

http://www.mathworks.com/help/images/performing-distinct-block-operations.html#bse_q4y-1

Although it's proprietary software, It may bring attention to the library, what could help in further development.

**Comment by boskar** [comment]
There is an alternative: OMERO matlab plugin. 

http://www.openmicroscopy.org/site/support/omero5.2/developers/Matlab.html 

However, it does not support everything openslide supports (i.e. does not support mrxs which is the format I use)

**Comment by bgilbert** [comment]
@boskar As far as I know, OMERO.matlab doesn't support OpenSlide at all.

Since @fordanic has kindly supplied [MATLAB bindings](https://github.com/fordanic/openslide-matlab), I'll close this bug.

**Comment by boskar** [comment]
You're right, OMERO uses its own stack. 

Thank You @fordanic!
