### ISSUE TITLE
Support NDPI files larger than 4 GB

### ISSUE THREAD

**Issue by malaterre** [openslide/openslide#136]
It would be nice to handle the funky BigTIFF from NDPI (> 4Gb). Right now I have:

$ openslide-show-properties micro.sdu.dk/media/bioformats/69.ndpi
openslide-show-properties: micro.sdu.dk/media/bioformats/69.ndpi: Not a file that OpenSlide can recognize

Refs: http://micro.sdu.dk/media/bioformats/

**Comment by bgilbert** [comment]
Fixed in master.
