### ISSUE TITLE
Support Philips exported TIFF files

### ISSUE THREAD

**Issue by JanOosting** [openslide/openslide#137]
The Philips slide scanner http://www.research.philips.com/initiatives/digitalpathology/approach.html by default stores slides in a proprietary format (iSyntax), but slides can be exported as tiff.
Openslide is able to handle these files as generic tiff files, but there is a shift of the image sometimes between magnifications.
I have made a slide available for viewing on https://www.leidenpastudy.nl/histoslide/slide/256/ to show the issue. The tiff file can be downloaded from https://www.leidenpastudy.nl/static/slides/PhilipsTest01.tiff 
I can make more slides available if needed.

The 'imagedescription' tag of the first image in the file contains an xml string that holds among others the pixel size of the slide. The 'software' tag contains "Philips DP v1.0".

Is it possible to change the origin of subimages to align them better with eachother ?

How do I extract the image properties to openslide-properties like openslide.mpp-y and openslide.mpp-x in the python bindings?

**Comment by JanOosting** [comment]
Dear Benjamin,

Thanks again for providing the ability to handle Philips tiff images. It helps us tremendously.
I have now finally asked my department head, and he has given permission to supply example scans.


Can you provide me with the forms that have to be signed?

Kind regards,

Jan

**Comment by bgilbert** [comment]
@JanOosting Thank you very much!  I'll email you the details.

**Comment by bgilbert** [comment]
@JanOosting Did you receive my email?  Is there anything I can do to help?

**Comment by mastaer** [comment]
hi,

i have current the same problems. have i done something wrong? or is this issue not fixed for ubuntu-user?

thx

**Comment by bgilbert** [comment]
@mastaer Philips TIFF is supported in OpenSlide 3.4.1, which hasn't yet been packaged for Debian or Ubuntu.  You can [install from source instead](http://openslide.org/download/).

**Comment by mastaer** [comment]
@bgilbert thank you :+1:

**Comment by tzayuan** [comment]
Hi @JanOosting 
Would you be so kind as to provide me with a download link to a `Philips TIFF file`?
