### ISSUE TITLE
Add API for reading slide ICC profiles

### ISSUE THREAD

**Issue by bgilbert** [openslide/openslide#139]
[Discussion](http://lists.andrew.cmu.edu/pipermail/openslide-users/2014-August/000904.html).

**Comment by dvdmena** [comment]
Connection with https://github.com/openslide/openslide/issues/237

Any news about?

**Comment by lukenovak** [comment]
@bgilbert would you have any recommendations for the general form of this API? I know there were concerns about keeping the profile in memory with `*openslide_get_profile(openslide_t *osr, size_t *length);`, but was curious if that was still a potential issue.

**Comment by bgilbert** [comment]
Yes, I'm told that some formats have multi-megabyte ICC profiles.  The application should provide the buffer, as it does with `openslide_read_region` and `openslide_read_associated_image`, but it'll need a way to get the buffer size.  I see a few possible approaches:

1. `uint64_t openslide_read_icc_profile(openslide_t *osr, void *dest, uint64_t len)`, where OpenSlide writes up to `len` bytes and returns the number of bytes it wanted to write.  That API is compact in some sense, but confusing, and requires the application to call the function twice.
2. `void openslide_read_icc_profile(openslide_t *osr, void *dest, uint64_t len)` and `uint64_t openslide_get_icc_profile_size(openslide_t *osr)`.  This is consistent with e.g. `openslide_get_level_dimensions`.
3. `void openslide_read_icc_profile(openslide_t *osr, void *dest, uint64_t len)`, where the profile size is stored in a property.  The application would have to convert the size property to an integer.

(`size_t` is traditional, but OpenSlide has managed to keep CPU-dependent field widths out of its public API, and I'm hesitant to start using them now.)

I think the right approach is probably 2.  We often _also_ put API-accessible metadata into properties, so that e.g. `openslide-show-properties` gives a complete picture, though notably we don't do that with associated images.

**Comment by bgilbert** [comment]
...and similarly for associated images (`openslide_get_associated_image_icc_profile_size` / `openslide_read_associated_image_icc_profile`), if we want to support profiles there.

We could perhaps drop the `len` argument, since the application knows how to size the buffer.  Notably the other `read` functions don't have one.

**Comment by lukenovak** [comment]
Good to know, and I think 2 or 3 are viable solutions. If 2 seems best to you, then that's probably the way forward. I don't think we'll need the `len` argument, or if we do we won't need to use it for tifflike slides.

Since each format could potentially store ICC profiles differently, how do you feel about offering the general API function and support for some but not all formats, at least at first? The path forward for tifflike slides seems straightforward enough to me, but I'm a little less experienced with other formats. If tifflike ends up ready to go quicker than everything else, would it be worth adding the function, and as a result the framework by which developers can this functionality for other formats, even if I only have a concrete implementation for tifflike?

**Comment by bgilbert** [comment]
> Since each format could potentially store ICC profiles differently, how do you feel about offering the general API function and support for some but not all formats, at least at first?

I think that's fine.  We'll need to conditionalize support anyway, since some formats don't provide ICC profiles.  Once the infrastructure is available, if certain formats are known to include profiles but OpenSlide doesn't support those, we should make sure to file issues to capture that.

**Comment by lukenovak** [comment]
Just to update this conversation- I have the main function implemented for TIFF-like slides. Haven't done the associated images work yet but I anticipate having that done relatively soon and putting a PR in.

**Comment by jetic83** [comment]
Hi @lukenovak do you think the main functions for ICC can be put in a PR already, even without ICC for associated images?

**Comment by bgilbert** [comment]
We're proceeding with #469, which I expect will land pretty soon.

**Comment by bgilbert** [comment]
Support for main image ICC profiles has landed.  I'll leave this open until we have support for associated image profiles.
