### ISSUE TITLE
help for a beginner...

### ISSUE THREAD

**Issue by muntesco** [openslide/openslide#149]
I am trying to implement virtual microscopy on my website........where should I start from, to connect open slide API to my wordpress site, or, in alternative to make a static webpage with openseadragon canvas displaying virtual slides? I am confident with css, and a less wit JS.
Other question is if it's possible to insert standard magnifications: 4x, 10x, 20x as on proprietary systems.
Thanks

**Comment by muntesco** [comment]
Well, thanks for the advices. I installed openslide, vips, python and all other staff. I realized rather easy how to display static tiles and now I am experimenting generating tiles and configuring vewer.
For static tiles I have a question: When runnind vips dzsave I get only myslide.dzi and myslide_files with layers. I do not get label and macro images. Also, I cant get properties.xml.

For the dynamic staff instead: I can't realize how to implement dynamic tiling. I am trying to get it on my local server (http:// localhost/~muntesco/), on Mac OS X laptop, but, can't realize how to visualize an svs file directly in openseadragon viewer.
Could you suggest to me a function to start from, or to insert in, or simply how to open svs file  in an OpenSeadragon viewer dynamic way??????

Thanks

**Comment by bgilbert** [comment]
To get `vips-properties.xml` you need to specify `--properties` to `vips dzsave`.  To get Deep Zoom trees for the label and macro images, you need to rerun `vips dzsave` and ask for the associated image you want:

```
vips dzsave CMU-1.svs[associated=label] label
vips dzsave CMU-1.svs[associated=macro] macro
```

You can run e.g. `deepzoom_server.py` with:

```
python openslide-python/examples/deepzoom/deepzoom_server.py /path/to/slide/file
```

Support questions are outside the scope of this bug tracker.  Please ask questions on the openslide-users mailing list.

**Comment by muntesco** [comment]
When running

python openslide-python/examples/deepzoom/deepzoom_server.py /path/to/slide/file

And still nothing. I can't get it work. It seems I 've installed all
the staff open slide, python, even flask seems to be present. still
nothing.

**Comment by anup36** [comment]
can you share more details am beginner in open slide, so can you share any tutorials or something which help me to use openslide.
