### ISSUE TITLE
Can't open Leica SCN files that have different XMLNS

### ISSUE THREAD

**Issue by joejacobs** [openslide/openslide#151]
I have quite a few Leica SCN files that OpenSlide doesn't recognise as Leica SCN files because the XMLNS is different.

OpenSlide checks for the following XMLNS: http://www.leica-microsystems.com/scn/2010/10/01
My SCN files (that I can't share unfortunately) have the following XMLNS: http://www.leica-microsystems.com/scn/2010/03/10

If I modify the LEICA_XMLNS constant in openslide-vendor-leica.c to use the "correct" XMLNS everything works fine. Perhaps it would be best to check if either namespace is present instead of just checking one?

**Comment by joejacobs** [comment]
Yup works fine. Thanks!

**Comment by bgilbert** [comment]
@joejacobs, do you have any 2010/03/10 slides that have a non-empty value for the `barcode` XML attribute?  For #155, I'm trying to find out whether the `barcode` in these older slides is in plain text (i.e., matches the bar code in the macro image) or is Base64-encoded (i.e., matches the bar code after it is run through `base64 -d`).

**Comment by joejacobs** [comment]
@bgilbert unfortunately I don't. All my slides have blank barcodes.

**Comment by bgilbert** [comment]
Okay, thanks for checking.
