### ISSUE TITLE
Incorrect Thumbnailfor Ventana Big Tiff

### ISSUE THREAD

**Issue by choosehappy** [openslide/openslide#153]
This is in conjunction with a Bisque image server issue:

https://groups.google.com/forum/#!topic/bisque-bioimage/fTjqWEc6u6s

The thumbnail created by openslide looks like this (black border added by me for visual purposes):

![image](https://cloud.githubusercontent.com/assets/9681868/6369655/abcd5f00-bce8-11e4-8f81-35087c4d8e13.png)

Where the image is pushed to the upper left hand corner.

While the actual second image layer contains this (loaded in matlab):

![image](https://cloud.githubusercontent.com/assets/9681868/6369420/6f21555e-bce6-11e4-8e69-caf68814e4fc.png)

I was able to reproduce this in python:

import openslide
obj=openslide.OpenSlide("upload.tif")
I=obj.get_thumbnail([150,150])
I.save('test.png')

**Comment by bgilbert** [comment]
Thanks for the report!  Could you post (or send to me privately) the affected slide file?

**Comment by choosehappy** [comment]
I'd be happy to!

You can download it from our bisque install here:

http://hawking.ebme.cwru.edu:8080/client_service/view?resource=http://hawking.ebme.CWRU.Edu:8080/data_service/00-XEqSKgvQ4NSicreAap23mc

If you use the Download button at the top left, there should be an "original" option which will get you the file.

just fyi, its about 900MB

let me know if you have any issues.

**Comment by bgilbert** [comment]
For me, OpenSlide is showing only the macro image.  Your Python fragment gives me this output:

![macro](https://cloud.githubusercontent.com/assets/361374/6385673/452d06b2-bd3b-11e4-81aa-b6a5d6fe6d89.png)

What version of OpenSlide are you using?

This file seems to be a variant of Ventana BIF with the tile overlaps resolved.  OpenSlide doesn't recognize the file (#147) and opens it with the generic TIFF driver, which doesn't have enough information to locate the pyramid levels within the file.

It looks as though it should be straightforward to support this Ventana variant within the existing driver.  Would you be able to provide a couple additional sample files?

**Comment by choosehappy** [comment]
It seem to be version 3.4.0:

[axj232@hawking ~]$ openslide-show-properties --version
openslide-show-properties 3.4.0, using OpenSlide 3.4.0
Copyright (C) 2007-2014 Carnegie Mellon University and others

I'm not sure if we're looking at the same index of the image. The one that you showed is from the first page. The thumbnail that openslide seems to be creating (that i posted above), seems to be created from the 2nd page. Here is a quick example in matlab:
First Page:
io=imread(fname,'Index',1);
imshow(io)

![image](https://cloud.githubusercontent.com/assets/9681868/6393590/c54f7448-bdcb-11e4-9c89-a9d76bc5077f.png)



Second Page:
io=imread(fname,'Index',2);
ims(io)

![image](https://cloud.githubusercontent.com/assets/9681868/6393595/cddc9032-bdcb-11e4-940a-02e5a91e8dc7.png)



So i'm guessing the python function .get_thumbail uses the 2nd one as the thumbnail and not the first. in actuality, either of them are fine, but the 2nd page thumbnail makes more "sense", as the other images in the stack are all of the same orientation and cropping. Is the issue that when the overlaps are resolved, but treated as if they aren't, the actual image becomes smaller than expected and placed over a white background of the expected size? 


I can provide as many examples as you need : )

Here are two more, with similar thumbnail issues:

![image](https://cloud.githubusercontent.com/assets/9681868/6393718/c981aecc-bdcc-11e4-8db8-a041f742e5b9.png)


http://hawking.ebme.cwru.edu:8080/client_service/view?resource=http://hawking.ebme.CWRU.Edu:8080/data_service/00-nGpANnmhatsQKTXqBi3K2a

http://hawking.ebme.cwru.edu:8080/client_service/view?resource=http://hawking.ebme.CWRU.Edu:8080/data_service/00-paoMyJ9QHTe6giCq3ttrb5

**Comment by bgilbert** [comment]
Thanks for the samples.

> Is the issue that when the overlaps are resolved, but treated as if they aren't, the actual image
> becomes smaller than expected and placed over a white background of the expected size?

The issue is that when the overlaps are resolved, the resulting TIFF is missing a piece of metadata that OpenSlide uses to identify the file as a Ventana slide.  It therefore falls back to the generic TIFF driver, which, as far as I can tell, cannot possibly produce the result you're seeing.  (None of the TIFF directories in these files have the reduced-resolution flag set, so the driver should be using the first directory and ignoring the others.)  That issue is probably academic, since the real fix is to support these files properly.  But I am curious why you're getting this result.

Could you run `openslide-show-properties` on one of the files and post its output?

**Comment by choosehappy** [comment]
Yes sir!

Here is the output from the first output.tif:

[root@hawking admin]# openslide-show-properties upload.tif
openslide.comment: 'level=0 mag=40 quality=90'
openslide.level-count: '11'
openslide.level[0].downsample: '1'
openslide.level[0].height: '35840'
openslide.level[0].width: '176128'
openslide.level[10].downsample: '1024'
openslide.level[10].height: '1024'
openslide.level[10].width: '1024'
openslide.level[1].downsample: '2'
openslide.level[1].height: '18432'
openslide.level[1].width: '88064'
openslide.level[2].downsample: '4'
openslide.level[2].height: '9216'
openslide.level[2].width: '44032'
openslide.level[3].downsample: '8'
openslide.level[3].height: '5120'
openslide.level[3].width: '22528'
openslide.level[4].downsample: '16'
openslide.level[4].height: '3072'
openslide.level[4].width: '11264'
openslide.level[5].downsample: '32'
openslide.level[5].height: '2048'
openslide.level[5].width: '6144'
openslide.level[6].downsample: '64'
openslide.level[6].height: '1024'
openslide.level[6].width: '3072'
openslide.level[7].downsample: '128'
openslide.level[7].height: '1024'
openslide.level[7].width: '2048'
openslide.level[8].downsample: '256'
openslide.level[8].height: '1024'
openslide.level[8].width: '1024'
openslide.level[9].downsample: '512'
openslide.level[9].height: '1024'
openslide.level[9].width: '1024'
openslide.mpp-x: '0.23250000000000001'
openslide.mpp-y: '0.23250000000000001'
openslide.objective-power: '40'
openslide.quickhash-1:
'29d6e942d349375ebbd752ffceed54ade15334103fde289b56f5498ebdc3d110'
openslide.vendor: 'ventana-tiff'
tiff.ImageDescription: 'level=0 mag=40 quality=90'
tiff.ResolutionUnit: 'inch'
ventana.BuildDate: 'January, 14 2014'
ventana.BuildVersion: '3.3.4.1'
ventana.FocusMode: '0'
ventana.FocusQuality: '1'
ventana.LabelBoundary: '1000'
ventana.Magnification: '40'
ventana.ScanMode: '1'
ventana.ScanRes: '0.23250'
ventana.ShowLabel: '1'
ventana.UnitNumber: 'BI13N0561'
ventana.Z-layers: '1'
ventana.Z-spacing: '1'
[root@hawking admin]#

**Comment by bgilbert** [comment]
> openslide.vendor: 'ventana-tiff'

Ah ha!  You're using a modified version of OpenSlide.  The version in this repo (the "official" version, I suppose) contains no such driver.  Where did you get your copy?

**Comment by choosehappy** [comment]
Okay, now that is a very interesting question....and things make a bit more
sense ;-)


I didn't personally do the installation on that machine, so i assumed it
was the repo version...


Digging around, it turns out, the guy (who has left) that installed it has
a github with a modified version:

https://github.com/abasavan/openslide

I've sent him an email trying to figure out where his version originated
from and i'll report back.

Not really sure where to go from here, i can of course install the official
version, but it seems neither the official or our modified version produce
the "optimal" thumbnail *and* recognize that file as ventana?

This is the output from the official version i have on another machine,
notice it does identify it as a "generic-tiff" exactly as you said:

axj232@ccipd-tesla-001:~/code/asoc$ openslide-show-properties upload.tif
openslide.comment: 'Label Image'
openslide.level-count: '1'
openslide.level[0].downsample: '1'
openslide.level[0].height: '3008'
openslide.level[0].tile-height: '3008'
openslide.level[0].tile-width: '1008'
openslide.level[0].width: '1008'
openslide.quickhash-1:
'27a1962b28eef05d02afe00abcdd2f828018fcbd91aed6f78591003b5270a322'
openslide.vendor: 'generic-tiff'
tiff.ImageDescription: 'Label Image'
tiff.ResolutionUnit: 'inch'

**Comment by bgilbert** [comment]
The code in that repo is not the code you're running: it's based on 3.3.3, which is a significantly different codebase from 3.4.0, and it reports itself as `ventana`.  There is also [cytomine/openslide](https://github.com/cytomine/openslide), which has some code to support Ventana TIFF, but it reports itself as `ventana tif`.  It's possible that you're using a more recent version of one of those branches that hasn't been pushed to GitHub.  All of which is fine, of course; I was just curious whether there was another branch out there with interesting changes in it.  :smiley: 

I hope to support this Ventana variant in the next release, which should be out within the next few weeks.  I'll let you know when I have a version to test.

**Comment by choosehappy** [comment]
I spoke with the guy who installed it. He said....long story short...no one knows where it came from, at least not easily. Given that as you say its already outdated, i think we'll just stick a fork in it and wait until the next release : )

**Comment by bgilbert** [comment]
This format should now be supported in Git master.  Feel free to try it out, and if you have any problems, please let me know.
