### ISSUE TITLE
Building produces odd error (OME)

### ISSUE THREAD

**Issue by Jondeen** [openslide/openslide#154]
Hi! 
Upon building openslide I get the following error:

(stage is --prefix dir)
**CCLD   src/libopenslide.la**
**./libtool: line 7475: cd: OME/stage/lib: No such file or directory**
**libtool:   error: cannot determine absolute directory name of 'OME/stage/lib'**

Any idea what may be the cause?

**UPDATE**
The --prefix is set to $HOME/stagedir. It seems the $H is expanded to "" which in turn leaves OME. This seems to specifically happen when it tries to parse the linker flags for openjpeg/jp2. I've pretty much built everything from source, so maybe it's a remnant from a prior link config... I'll come back with results after further checks. After manually replacing with absolute paths in Makefile the build seems to succeed.

**Comment by bgilbert** [comment]
I'd guess that you're passing `$HOME` in single quotes, e.g. `--prefix='$HOME'`, which prevents the shell from expanding it before passing it to configure.  That would cause the literal string `$HOME` to be embedded in the Makefile, and Make would then expand `$H` to "" as you say.  (The Make syntax for variable expansion is `$(HOME)`.)

Try `--prefix="$HOME"` instead.

**Comment by Jondeen** [comment]
Roger :+1: 

Thanks for feedback!
