### ISSUE TITLE
Decode leica barcode

### ISSUE THREAD

**Issue by malaterre** [openslide/openslide#155]
It would be nice if the barcode from leica (*.scn) would be decoded (much easier to read).

Eg:

$ tiffinfo Leica-1.scn| grep barcode
    <barcode>MDQwNTA2MjlD</barcode>
$ echo MDQwNTA2MjlD | base64 -d 
04050629C%            

The following line would need to be adapted:

  // Get barcode as stored in 2010/10/01 namespace
  collection->barcode = _openslide_xml_xpath_get_string(ctx, "/d:scn/d:collection/d:barcode/text()");

Thanks !

**Comment by bgilbert** [comment]
Argh, I hadn't realized the barcode was a Base64-encoded string.  Thanks for the report.

Fixing this will break compatibility with applications using that property.  The alternatives are worse (adding `leica.decoded-barcode`, or documenting the property as Base64-encoded), but perhaps we need to make it easier for applications to implement compatibility workarounds for particular versions of OpenSlide.

Also, update the website to document that older versions Base64-encode the property.

**Comment by malaterre** [comment]
I personnally like the ```leica.decoded-barcode```, what if tomorrow a vendor start storing a barcode as QR code. It would make sense for openslide to provide both the ```barcode``` and the ```decoded``` one.

my 2cts

**Comment by bgilbert** [comment]
I'm not sure I understand your point.  If the QR code is stored as pixels, we would expose it in the `label` associated image, as we do now for several formats.  If the contents of the QR code are stored, we would expose them as a string or numeric property.  How would a Base64-encoded property help anyone?

In any event, `leica.barcode` is a vendor-specific property, so we don't need to be concerned with other vendors here.

**Comment by bgilbert** [comment]
Also, you said:

> The following line would need to be adapted:
> 
> // Get barcode as stored in 2010/10/01 namespace
> collection->barcode = _openslide_xml_xpath_get_string(ctx, "/d:scn/d:collection/d:barcode/text()");

Do you have evidence that the 2010/03/10 namespace doesn't also Base64-encode the barcode?

**Comment by malaterre** [comment]
Without specifications I cannot answer. I simply *assumed* that barcode was encoded in base64 (which proved correct so far).

**Comment by malaterre** [comment]
The terminology I used for ```decoded``` was an opaque transformation from the stored representation to a human readable representation (eg. QR code string -> QR decoded string). It is very vague and mostly academic debate since it was only a (poor) example to find a solution to the ```leica.barcode``` vs ```leica.decoded_barcode``` initial issue.

**Comment by bgilbert** [comment]
OK, thanks for the clarifications.

**Comment by bgilbert** [comment]
Fixed for `2010/10/01` namespace only.  The `2010/03/10` namespace puts the barcode in a different place and I don't have any evidence on whether it is also Base64-encoded, so I haven't changed how those slides are handled.  If anyone has a `2010/03/10` slide with a barcode and can verify whether or not the `barcode` attribute is Base64-encoded, please comment here.
