### ISSUE TITLE
Extracting fluorescence channel images with openslide

### ISSUE THREAD

**Issue by assilbenchaaben** [openslide/openslide#160]
Hi,

Is there any way for extracting fluorescence channel images on Hamamatsu ndpi image using openslide. I search the internet and i found that some people ask the same think (that was in 2013). Scince that dis someone add openslide API to support  fluorescence channel.

**Comment by bgilbert** [comment]
Not yet.  See #42.

Can you provide sample NDPI files with fluorescence imagery?

**Comment by assilbenchaaben** [comment]
Thank you for response. Sorry i can't provide those images, i'm not the owner.

**Comment by maryamsss** [comment]
Hello,
I also have the same issue, that I need to extract flourocent channels sepparately for a mirax file. I call also share the mrxs file if needed.
