### ISSUE TITLE
3DHistech .mrxs v2.2 reads only Zero

### ISSUE THREAD

**Issue by the-s-a-m** [openslide/openslide#164]
If I want to read the 3DHistech .mrxs v2.2 format the reader just returns zeros. Is it a api error?
![17-09-2015 08-05-06](https://cloud.githubusercontent.com/assets/6050624/9926113/e3c5e4a2-5d12-11e5-9309-08de9d440c3d.png)

the function I called: openslide_read_region();

Thank you for checking

**Comment by bgilbert** [comment]
MRXS slides often have large regions containing no pixel data.  OpenSlide renders these with transparent pixels, which are numerically zero.  That's what you're seeing here.  You're advancing the `openslide_read_region()` `x` and `y` parameters by one pixel per call, not one tile, so you're really only reading the top-left corner of the slide.

**Comment by the-s-a-m** [comment]
Thank you
