### ISSUE TITLE
VMS .opt file parsed incorrectly when there are multiple Z-layers

### ISSUE THREAD

**Issue by tseytlin** [openslide/openslide#165]
Some VMS files cannot open if .opt file is there.

OpenSlide.createThumnailImage() and OpenSlide.paintRegion() methods (in Java bindings) both 
return
 java.io.IOException: Restart marker not found at recorded position 1675538

meta information is returned though.
After reading about VMS on openslide site, I tried renaming the .opt file and the .VMS files opens successfully. 

Perhaps OpenSlide library should ignore the .opt file if it can't successfully use it.

**Comment by bgilbert** [comment]
Could you send me an affected slide?

**Comment by tseytlin** [comment]
That's tricky. Slide contains a label  with PHI, so I can't just send you a file. 
I can ask my PI if I can,  and if so, maybe send you an encrypted 7zip file directly. 
My direct email is tseytlin@pitt.edu

**Comment by bgilbert** [comment]
Is there any commonality among the affected slides?  (E.g., they were all scanned on the same scanner, or with the same version of the software.)  If so, you might be able to create an affected slide without any PHI.

You could perhaps remove the PHI by omitting the `_macro` file (which contains the label) and deleting any barcode data from the `.vms` file.

**Comment by tseytlin** [comment]
I actually talked to my boss, she is OK with sending you a vms file with
doctored map file.

**Comment by tseytlin** [comment]
what email I can use to send you a download link for a file?

**Comment by bgilbert** [comment]
Use bgilbert@cs.cmu.edu.

**Comment by tseytlin** [comment]
just sent you an image via DataDepot

**Comment by bgilbert** [comment]
It looks as though a couple files are missing: the layer-0 image file (`<filename>.jpg`) and the actual `.opt` file.  Could you send me those as well?

**Comment by bgilbert** [comment]
Thanks for the report and sample.  OpenSlide is incorrectly handling the `.opt` file for slides with multiple Z-layers.  I don't currently have enough information to know how to fix this.  Do you have any slides with multiple Z-layers whose width or height (preferably both) is greater than 65000 pixels?  Could you send me one?

**Comment by tseytlin** [comment]
I am having issues using the latest openslide library on Linux (Ubuntu 
12.04.5 LTS)
I tried doing both apt-get and compiling from source.

I can open hamamatsu images and others, but Aperio images (demo test 
images on openslide site) don't work.

[micron]~> /usr/local/bin/openslide-write-png ~/Downloads/CMU-1.svs 0 0 
1 500 500 test.png
openslide-write-png: Unsupported color conversion request


[micron]/usr/local/lib> ldd /usr/lib/libopenslide.so.0
     linux-vdso.so.1 =>  (0x00007ffd0fd8d000)
     libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 
(0x00007fbc0d8ec000)
     libcairo.so.2 => /usr/lib/x86_64-linux-gnu/libcairo.so.2 
(0x00007fbc0d62e000)
     libtiff.so.4 => /usr/lib/x86_64-linux-gnu/libtiff.so.4 
(0x00007fbc0d3c9000)
     libopenjpeg.so.2 => /usr/lib/libopenjpeg.so.2 (0x00007fbc0d1a8000)
     libjpeg.so.8 => /usr/lib/x86_64-linux-gnu/libjpeg.so.8 
(0x00007fbc0cf58000)
     libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fbc0cc5b000)
     libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 
(0x00007fbc0ca3e000)
     libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fbc0c680000)
     libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007fbc0c442000)
     librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fbc0c23a000)
     libpixman-1.so.0 => /usr/lib/x86_64-linux-gnu/libpixman-1.so.0 
(0x00007fbc0bfa3000)
     libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 
(0x00007fbc0bd6c000)
     libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 
(0x00007fbc0bacf000)
     libpng12.so.0 => /lib/x86_64-linux-gnu/libpng12.so.0 
(0x00007fbc0b8a7000)
     libxcb-shm.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-shm.so.0 
(0x00007fbc0b6a3000)
     libxcb-render.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-render.so.0 
(0x00007fbc0b499000)
     libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 
(0x00007fbc0b27b000)
     libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1 
(0x00007fbc0b070000)
     libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 
(0x00007fbc0ad3b000)
     libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fbc0ab24000)
     /lib64/ld-linux-x86-64.so.2 (0x00007fbc0de1a000)
     libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 
(0x00007fbc0a8f9000)
     libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 
(0x00007fbc0a6f6000)
     libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 
(0x00007fbc0a4ef000)
     libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fbc0a2eb000)

I was using the Java bindings as well, I don't see any errors, but 
neither do I see any tissue :)

I suspect that this is related to some libtiff library issue, but I 
can't figure out how to get a working linux OpenSlide library that works 
for Aperio

Any suggestions? Please help.


Eugene

**Comment by bgilbert** [comment]
@tseytlin Any news on this?  I'd love to fix this bug but I don't have enough information right now.

**Comment by tseytlin** [comment]
I don't think I have any files with multiple z layers. I thought I sent you
a file that was not working. Was it not enough to replicate this issue?

**Comment by bgilbert** [comment]
I did replicate the issue with the slide you sent me.  The slide has three Z-layers (`NoLayers=3` in the `.vms` file), which causes OpenSlide to parse the `.opt` file incorrectly.  To figure out how to correctly read the `.opt` file in this case, I need to see a slide which has multiple JPEGs per layer -- that is, a slide larger than 65000 pixels on one or both axes -- and which also has multiple Z-layers.  Can you provide such a slide?  I don't have access to any slide scanners myself.

**Comment by tseytlin** [comment]
Just emailed you the link via your personal email to the largest 
hamamatsu file I have with 75K x 41K dimensions
Hope that helps.

**Comment by bgilbert** [comment]
This should be fixed in master; let me know if it's still not working for you.  Thanks for the report!

**Comment by tseytlin** [comment]
Thank you
