### ISSUE TITLE
Integrate for iOS Application

### ISSUE THREAD

**Issue by gauravthummar** [openslide/openslide#167]
I need to integrate this library with iOS application. 
How can i use this library for read image in my ios app.
please provide me any manual or guide that help me to integrate this library with my iOS App.

**Comment by gauravthummar** [comment]
#include <config.h> this file not found.
please let me know about where i got this file.

**Comment by gauravthummar** [comment]
#include <tiffio.h> this file not found.

**Comment by bgilbert** [comment]
I haven't tried running OpenSlide on iOS.  You would need to build OpenSlide plus all of its dependencies (libjpeg, libtiff, glib, cairo, etc.), which is a non-trivial amount of work.  You could try asking the [openslide-users mailing list](https://lists.andrew.cmu.edu/mailman/listinfo/openslide-users/) whether anyone else has done this.
