### ISSUE TITLE
deployment on a webserver

### ISSUE THREAD

**Issue by muntesco** [openslide/openslide#170]
My webserver supports python. 
However it is not a dedicated server so no way to install Flask and other dependencies. 

Do I need to install flask and other staff in order to run my .svs slides dinamically (as I did it on my local machine)? 
For this I need to upgrade to VPS (that wouldn't be a great problem)

**Comment by bgilbert** [comment]
Yes.

As I've [already](https://github.com/openslide/openslide/issues/150#issuecomment-65892193) [told](https://github.com/openslide/openslide/issues/149#issuecomment-71591984) you, support questions should be directed to the openslide-users mailing list.  Support questions about other software, such as Flask, should be directed to the support channels for that software.
