### ISSUE TITLE
SVS opens in Aperio ImageScope but not OpenSlide or OpenMicroscopy BioFormats

### ISSUE THREAD

**Issue by aday00** [openslide/openslide#173]
This SVS file doesn't open in OpenSlide or BioFormats:
https://drive.google.com/file/d/0B-VvG_q1MZzkM1d6aGl3Vy1zams/view?usp=sharing

However, it opens fine in ImageScope, small screenshot here:
https://drive.google.com/file/d/0B-VvG_q1MZzkel9KeTJNU0lEblE/view?usp=sharing

OpenSlide says:
`$ openslide-show-properties K101081.svs
openslide-show-properties: K101081.svs: Not a file that OpenSlide can recognize`

More verbosely:
`$ ltrace openslide-show-properties K101081.svs
__libc_start_main(0x400df0, 2, 0x7ffe1409e6d8, 0x4012b0 <unfinished ...>
g_option_context_new(0x4015e2, 0x7ffe1409e5bc, 0x7ffe1409e5b0, 0)                                = 0x1ad84e0
g_option_context_set_summary(0x1ad84e0, 0x401598, 8, 16)                                         = 0x1ad8540
g_option_context_add_main_entries(0x1ad84e0, 0x401500, 0, 80)                                    = 0
g_option_context_parse(0x1ad84e0, 0x7ffe1409e5bc, 0x7ffe1409e5b0, 0x7ffe1409e560)                = 1
g_option_context_free(0x1ad84e0, 0x7ffe1409e6d8, 0x7ffe1409e6e0, 0)                              = 0
openslide_open(0x7ffe1409fdea, 0x7ffe1409fdea, 2, 0x7ffe1409e6d8)                                = 0
g_get_prgname(0, 0, 0, 0)                                                                        = 0x1ad8660
__fprintf_chk(0x7f26e1b0b060, 1, 0x401560, 0x1ad8660openslide-show-properties: K101081.svs: Not a file that OpenSlide can recognize
)                                            = 80
fflush(0x7f26e1b0b060)                                                                           = 0
+++ exited (status 1) +++`

For completeness, I've also tried opening this SVS in BioFormats, which failed with a stack trace:
https://www.openmicroscopy.org/site/products/bio-formats
`loci.formats.FormatException: No IFDs found
    at loci.formats.in.MinimalTiffReader.initFile(MinimalTiffReader.java:446)
    at loci.formats.in.BaseTiffReader.initFile(BaseTiffReader.java:576)
    at loci.formats.FormatReader.setId(FormatReader.java:1426)
    at loci.plugins.in.ImportProcess.initializeFile(ImportProcess.java:505)
    at loci.plugins.in.ImportProcess.execute(ImportProcess.java:143)
    at loci.plugins.in.Importer.showDialogs(Importer.java:140)
    at loci.plugins.in.Importer.run(Importer.java:76)
    at loci.plugins.LociImporter.run(LociImporter.java:78)
    at ij.IJ.runUserPlugIn(IJ.java:199)
    at ij.IJ.runPlugIn(IJ.java:163)
    at ij.Executer.runCommand(Executer.java:132)
    at ij.Executer.run(Executer.java:65)
    at java.lang.Thread.run(Unknown Source)`

So I think there's something unusual with this SVS.  Any help greatly appreciated!
-Andrew

**Comment by bgilbert** [comment]
Your file has a valid TIFF header, which claims that the first TIFF directory is 181 MB into the file.  However, the file is only 16 MB.  In addition, the last JPEG in the file is incomplete (it's cut off in the middle of the entropy-coded segment).  So it appears to me that the file has been truncated.  How did you get it?  Are you certain that the file is correctly opened by ImageScope?

**Comment by aday00** [comment]
Thanks very much!  I redownloaded, all 181MB, and the file opened fine in
openslide.

**Comment by bgilbert** [comment]
Sounds good, glad it worked out.
