### ISSUE TITLE
Openlayers with openslide

### ISSUE THREAD

**Issue by selko** [openslide/openslide#179]
Hi all! Is it possible to open an image via deep-zoom (openslide-python) in Openlayers like in the Openseadragon example?

**Comment by bgilbert** [comment]
OpenLayers doesn't seem to support Deep Zoom, but it does support other zoomable image formats such as Zoomify.  One approach, if it makes sense for your use case, is to generate a Zoomify directory using `vips dzsave --layout=zoomify` and serve it to OpenLayers using a standard webserver.  If, instead, you want to generate individual image tiles on request (as `deepzoom_server.py` does) you'll need to implement something like `openslide.deepzoom.DeepZoomGenerator` for Zoomify or a similar format.

In the future, please send support questions to the openslide-users mailing list.  Thanks!
