### ISSUE TITLE
when I make the openslide, I got bugs related to libtiff 

### ISSUE THREAD

**Issue by brisker** [openslide/openslide#180]
How to build?

./configure
make
make install

(If building from the Git repository, you will first need to install
autoconf, automake, libtool, and pkg-config and run "autoreconf -i".)
I follow the steps in https://github.com/uclouvain/openjpeg/blob/master/INSTALL.md
and all went well when I run "make",
and the bugs read like this:

src/.libs/libopenslide.so: undefined reference to TIFFIsTiled@LIBTIFF_4.0' src/.libs/libopenslide.so: undefined reference toTIFFRGBAImageEnd@LIBTIFF_4.0'
src/.libs/libopenslide.so: undefined reference to TIFFRGBAImageOK@LIBTIFF_4.0' src/.libs/libopenslide.so: undefined reference toTIFFClientOpen@LIBTIFF_4.0'
src/.libs/libopenslide.so: undefined reference to TIFFFileName@LIBTIFF_4.0' src/.libs/libopenslide.so: undefined reference toTIFFCurrentDirectory@LIBTIFF_4.0'
src/.libs/libopenslide.so: undefined reference to TIFFIsCODECConfigured@LIBTIFF_4.0' src/.libs/libopenslide.so: undefined reference toTIFFComputeTile@LIBTIFF_4.0'
src/.libs/libopenslide.so: undefined reference to TIFFGetField@LIBTIFF_4.0' src/.libs/libopenslide.so: undefined reference toTIFFRGBAImageGet@LIBTIFF_4.0'
src/.libs/libopenslide.so: undefined reference to TIFFSetDirectory@LIBTIFF_4.0' src/.libs/libopenslide.so: undefined reference toTIFFGetFieldDefaulted@LIBTIFF_4.0'
src/.libs/libopenslide.so: undefined reference to TIFFRGBAImageBegin@LIBTIFF_4.0' src/.libs/libopenslide.so: undefined reference toTIFFClose@LIBTIFF_4.0'
src/.libs/libopenslide.so: undefined reference to TIFFReadRawTile@LIBTIFF_4.0' src/.libs/libopenslide.so: undefined reference toTIFFReadDirectory@LIBTIFF_4.0'

I have successfully build openslide previously(without opencv), but today I reinstall my ubuntu system and cmake the opencv with libtiff on(cmake -D BUILD_TIFF=ON ..) .So is the error cause by this? If so, could you please tell me how to fix this?(I have tried to cmake the openjpeg with libtiff on, but error again)

**Comment by bgilbert** [comment]
We don't handle support requests in the OpenSlide issue tracker.  Please send your questions to the [openslide-users mailing list](https://lists.andrew.cmu.edu/mailman/listinfo/openslide-users/).
