### ISSUE TITLE
Enable buildbot integration

### ISSUE THREAD

**Issue by agoode** [openslide/openslide#193]
I enabled travis integration in #191. This minimal integration gives an example of how tests can automatically run at pull request time.

We should update the buildbot configuration to enable such integration and then remove the travis config.

**Comment by bgilbert** [comment]
For the record, the Travis config currently consists of an openslide/openslide repository hook, openslide/openslide/.travis.yml, and the Travis-side setup.

**Comment by agoode** [comment]
The travis stuff is now removed, except for the .travis.yml file itself.

**Comment by bgilbert** [comment]
CI is now running on PRs via GitHub Actions, and `travis.yml` has been removed.  I'll close this.
