### ISSUE TITLE
Audit security options pages

### ISSUE THREAD

**Issue by agoode** [openslide/openslide#194]
There are lots of new options for teams and collaboration now. We should go through and decide if any changes are needed.

https://github.com/organizations/openslide/settings/member_privileges
https://github.com/organizations/openslide/settings/oauth_application_policy
https://github.com/openslide/openslide/settings/collaboration

**Comment by bgilbert** [comment]
Everything is already configured as restrictively as possible, except that we allow all third-party applications.  I'd like to switch to whitelisting instead.  Any objections?

**Comment by agoode** [comment]
do it

**Comment by bgilbert** [comment]
Done.
