### ISSUE TITLE
 Openslide can read the remote slide on internet?

### ISSUE THREAD

**Issue by lovple** [openslide/openslide#200]
Hi All, 
I have a project need to use the Openslide to read the remote file,as like "http://www.xxx.com/xxx.ndpi"
is it working? Our development language is C#

## Context

**Issue type** (bug report or feature request): 
**Operating system** (e.g. Fedora 24, Mac OS 10.11, Windows 10): 
**Platform** (e.g. 64-bit x86, 32-bit ARM): 
**OpenSlide version**: 
**Slide format** (e.g. SVS, NDPI, MRXS):

**Comment by bgilbert** [comment]
See [this discussion](https://lists.andrew.cmu.edu/pipermail/openslide-users/2016-April/001236.html) on the openslide-users mailing list.
