### ISSUE TITLE
Node.js bindings

### ISSUE THREAD

**Issue by xmkevin** [openslide/openslide#204]
Hi, is there any plan for developing an node bindings ?

thanks.

**Comment by bgilbert** [comment]
Not that I know of.  If you or anyone else would like to do it, I'm sure the community would be interested in using them!  I'd be happy to answer implementation-related questions on the [openslide-users mailing list](https://lists.andrew.cmu.edu/mailman/listinfo/openslide-users/).

**Comment by xmkevin** [comment]
Thanks. I have subscribed the mailing list. Since I don't familiar with c++, I will try my best to implement one.

**Comment by bgilbert** [comment]
Reopening to keep a record of the request.

**Comment by jcupitt** [comment]
I don't know if it would fit your needs, but sharp supports openslide file read:

https://github.com/lovell/sharp
http://sharp.dimens.io/en/stable/

It'll let you pull out areas from specific layers and render to jpg/png/whatever, in a buffer, stream or file. It has a nice, fluent, promise-based API and is well supported on Linux, macOS and Windows. It's just `npm install sharp` to get started, though you may need to enable openslide support, depending on your platform.

**Comment by xmkevin** [comment]
@jcupitt Thanks. What we need is to read the existing vendor independent file formats, sharp doesn't support this.

**Comment by jcupitt** [comment]
@xmkevin, sharp can read all the formats that openslide can read, you just need to enable openslide support. There are some notes in the README.

**Comment by xmkevin** [comment]
@jcupitt Thank you very much.  I just check the README, I don't find any documents about openslide. Can you give me a link ?  Thanks.

**Comment by jcupitt** [comment]
There's now an experimental node binding for the whole of libvips here:

https://github.com/jcupitt/node-vips

I'm not much of a node programmer, so though it works, it needs some finishing up.

**Comment by jcupitt** [comment]
I added an openslide example to show the API:

```javascript
var vips = require('vips');

// get a rect from a level
// autocrop trims off pixels outside the image bounds
var image = vips.Image.openslideload('somefile.svs', {level: 2, autocrop: true});
console.log('level size:', image.width, 'x', image.height);
// try 'vipsheader -a somefile.svs' at the command-line to see all the metadata
// fields you can get
console.log('associated images are:', image.get('slide-associated-images'));
// crop is left, top, width, height in pixels
// images are RGBA with premultiplication taken out
image.crop(100, 100, 1000, 1000).writeToFile('x.png');

// extract an associated image
image = vips.Image.openslideload('somefile.svs', {associated: 'label'});
image.writeToFile('label.png');
```

It supports async too:

https://github.com/jcupitt/node-vips/blob/master/example/openslide-async.js

**Comment by bgilbert** [comment]
This issue has been inactive for a while, so I'll go ahead and close.  Anyone who wants to implement additional language bindings is still more than welcome to do so, and I'd be happy to help answer any implementation questions they may have.
