### ISSUE TITLE
Unable to use paths as filenames

### ISSUE THREAD

**Issue by cdekkers** [openslide/openslide#206]
## Context

**Issue type** Feature request
**Operating system** Windows 10
**Platform** 64-bit x86
**OpenSlide version**: 3.4.1
**Slide format**: N/A 

## Details
Using VS2015, I seem to be unable to pass paths (e.g. `"../CMU-1.tiff"`) to the `filename` argument of the following functions: `openslide_detect_vendor (const char *filename)`, `openslide_open (const char *filename)`, and `openslide_can_open (const char *filename)`. Using backslashes (e.g. `"..\CMU-1.tiff")` or escaped backslashes (e.g. `"..\\CMU-1.tiff"`) won't work either. Neither does using full paths (e.g. `"C:\\Path\\to\\CMU-1.tiff"`). Only when the image `CMU-1.tiff` is in the same directory as my VS executable, am I able to obtain desired outputs from these functions. But I prefer not to put any whole-slide images into that directory.

Is this functionality available? Might be overlooking something silly.

Thank you.

**Comment by bgilbert** [comment]
Backslashes should work with either relative or absolute paths.  Of course, they must be escaped if put in string literals.  If the `*filename` contains non-ASCII characters, 3.4.1 will fail on Windows, but Git master should work (with UTF-8 strings).

You can try setting the `OPENSLIDE_DEBUG` environment variable to `detection`, which should produce some debug logging on stderr.

**Comment by cdekkers** [comment]
This issue occured when developing an app for the Universal Windows Platform (UWP). UWP apps require explicit user permissions to access files or folders outside of a few predetermined directories. This has been implemented as a means of security and is the cause of this issue. More can be found here: https://docs.microsoft.com/en-us/windows/uwp/files/file-access-permissions
