### ISSUE TITLE
Read .SCN Error

### ISSUE THREAD

**Issue by DaihuaWei** [openslide/openslide#216]
## Context
when i read a .SCN files  in python，report the error below:

openslide.lowlevel.OpenSlideError: Slides with dissimilar main images are not supported

**Comment by bgilbert** [comment]
Duplicate of #99 or #189.

**Comment by akulkarniNephrosant** [comment]
is this resolved? I am having the same issue as above
openslide.lowlevel.OpenSlideError: Slides with dissimilar main images are not supported
