### ISSUE TITLE
Openslide not importing in python

### ISSUE THREAD

**Issue by manibk31** [openslide/openslide#220]
## Context
Bug
Windows 10
64-bit

## Details

I tried to import open slide, it won't open because of the following reason:

"The procedure entry point inflateValidate could not be located in the dynamic link library C:\openslide\bin\libpng16-16.dll"

Could somebody please help/suggest a solution? Thank you

**Comment by manibk31** [comment]
EDIT: Actually I did not build it from source, instead, downloaded the binaries directly. Last year's release works like a charm!

**Comment by garibarba** [comment]
Same thing on Windows 7 64-bit.

Using:
* openslide-python 1.1.1 from pip
* Windows Binaries from 2017-11-22

Error:
"The procedure entry point inflateValidate could not be located in the dynamic link library C:\openslide\bin\zlib1.dll"

Solution:
Use Window Binaries from 2016-07-17

**Comment by bgilbert** [comment]
Duplicate of openslide/openslide-winbuild#17
