### ISSUE TITLE
Bug with openslide_read_region on any levels other than 0

### ISSUE THREAD

**Issue by ade90036** [openslide/openslide#222]
## Context

**Issue type** BUG: 
**Operating system** Mac OS 10.11: 
**Platform** x86_64: 
**OpenSlide version**: MASTER 
**Slide format** SVS: 

## Details

I created program to take an image (in my case the CMU-1.svs) and create a tiff for each level with a different tile size (from 256 to 512).

Because i need to do some other image stuff i'm using **openslide_cairo_read_region** function.

The image as you know has the following levels:

```
property: openslide.level-count -> 3
property: openslide.level[0].downsample -> 1
property: openslide.level[0].height -> 32914
property: openslide.level[0].tile-height -> 256
property: openslide.level[0].tile-width -> 256
property: openslide.level[0].width -> 46000
property: openslide.level[1].downsample -> 4.0001215362177929
property: openslide.level[1].height -> 8228
property: openslide.level[1].tile-height -> 256
property: openslide.level[1].tile-width -> 256
property: openslide.level[1].width -> 11500
property: openslide.level[2].downsample -> 16.000486144871171
property: openslide.level[2].height -> 2057
property: openslide.level[2].tile-height -> 256
property: openslide.level[2].tile-width -> 256
property: openslide.level[2].width -> 2875
property: openslide.quickhash-1 -> 30f1a38031fc0e21d81f9d01435ac4af848f6fe2bbf8f7768184336ee5d7e796
property: openslide.vendor -> aperio
```

The program runs as expected on level 0: 

```
read_region --> x(0), y(0), w(512), h(512), level(0)
read_region --> x(512), y(0), w(512), h(512), level(0)
read_region --> x(1024), y(0), w(512), h(512), level(0)
read_region --> x(1536), y(0), w(512), h(512), level(0)
```
But then the program moves on to level(1), the outputted image seems to be repeating, or somehow read from a different level (image attached)

```
read_region --> x(0), y(0), w(512), h(512), level(1)
read_region --> x(512), y(0), w(512), h(512), level(1)
read_region --> x(1024), y(0), w(512), h(512), level(1)
read_region --> x(1536), y(0), w(512), h(512), level(1)
```

From what i can see the function is inconsistent when the level is changed.

**Comment by ade90036** [comment]
here is the image: 




I can provide more details if required.

Regards

ade90036

**Comment by ade90036** [comment]
Ok,

because the cairo function shouldn't be public, i thought this could be related to an untested functionality.

Therefore i have changed the algorithm to use the standard function: **openslide_read_region**

However, I'm observing the same behaviour. 

When i reading a region from another level it is coming back mangled.

**Comment by ade90036** [comment]
this is the program i'm using, if you want to reproduce it with...

[extract.txt](https://github.com/openslide/openslide/files/1608975/extract.txt)

run it with  test/extract ../images/CMU-1.svs

check your current directoty.

test_0.tiff ==  OK
test_1.tiff == Mangled
test_2.tiff == Mangled

**Comment by bgilbert** [comment]
As the [openslide_read_region documentation](http://openslide.org/api/openslide_8h.html#a0eeecec682efdf2ef18c8426109acad0) says, the x and y parameters are always in the coordinate space of level 0.  For the behavior you want, you'll need to multiply those parameters by the downsample of the level you're reading.

**Comment by ade90036** [comment]
Balls, i have underlooked that piece of information. Thanks Ben.

**Comment by ade90036** [comment]
After reading a bit more into this i have one more question.

If i iterate through the level1 and then calculate the x,y from level0 by multiply by the downsample i'm going to get into two troubles.

1. What am i going to use to round the x/y coordinates? (round(x), floor(x), floor(x+0.5)
2. If i'm using level1 as the space to iterate this will introduce inconsistencies. 

For example:
```
property: openslide.level[0].downsample -> 1
property: openslide.level[0].height -> 32914
property: openslide.level[0].tile-height -> 256
property: openslide.level[0].tile-width -> 256
property: openslide.level[0].width -> 46000
property: openslide.level[1].downsample -> 4.0001215362177929
property: openslide.level[1].height -> 8228
property: openslide.level[1].tile-height -> 256
property: openslide.level[1].tile-width -> 256
property: openslide.level[1].width -> 11500
```
(height from level1) 8228*4.0001215362177929 = 32913 and not 32914 from level0
(width from level1) 11500*4.0001215362177929 = 46001 and not 46000 from level0

So do you have a recommended way to iterate through the level1 and avoid miss-alignment and offset which would introduced by the rounding issues?

Should i use the level0 as the space to iterate in all the levels?

Regards

ade

**Comment by ade90036** [comment]
Ok, i have managed with the suggested reccomendation. I have changed the algorithm to use the space level reference from level0 and the results are good. 

Thanks again.

Regards

ade
