### ISSUE TITLE
Is there whole slide Image creator?

### ISSUE THREAD

**Issue by artzers** [openslide/openslide#223]
## Context
**Slide format** (e.g. SVS, NDPI, MRXS): 
We have many small image blocks of which the total volume is above 10GB, instead of a large image. We want to create a whole slide image. Do you have any tools? Thanks

**Comment by bgilbert** [comment]
Take a look at [VIPS](https://jcupitt.github.io/libvips/).  You can use it to composite a large number of images together, then write out a pyramidal tiled TIFF.
