### ISSUE TITLE
undefined reference to `openslide_open'

### ISSUE THREAD

**Issue by liuzhisheng1226** [openslide/openslide#224]
I install openslide ,But when I exec gcc test.cpp ，it shows undefined reference to `openslide_open'
#include<openslide.h>
#include <stdint.h>
int main(){
        openslide_t *file=openslide_open("Tumor_023.tif");
        return 0;
}

**Comment by bgilbert** [comment]
Did you remember to link against the OpenSlide library?

**Comment by liuzhisheng1226** [comment]
Thanks，I solved it
