### ISSUE TITLE
How do i enable IDE debugging?

### ISSUE THREAD

**Issue by ade90036** [openslide/openslide#231]
## Context

**Issue type**: 
**Operating system**: Ubuntu 17.10 
**Platform**: x86_64 
**OpenSlide version**: master
**Slide format**: Philips Tiff 

## Detail
I have tried to extract a whole region but the images doesn't resembles anything from the original image.

I have compiled all the code from master and I have it running locally my IDE. 
Is there a way to build the openslide with the debug symbols, because i can only DEBUG steps of my program and it doesn't allow me to step inside any of the openslide functions. 

Help would be extremely appreciated. 

I'm sure there is a switch or environment i need to enable from the make command but it is not documented.

Code seems to be compiled without any debugging symbols. 

regards

Andrea

**Comment by bgilbert** [comment]
If you're building from source, the debug symbols should be enabled by default.  You may want to verify that you're using the copy of OpenSlide that you built from source, and not the copy packaged in Ubuntu.

**Comment by ade90036** [comment]
Thanks for the reply. 

Yes, you were right, the program was linking to the installed OpenSlide libraries. 
Now that i have removed them (apt remove libopenslide0) when i start the debugged in netbeans it complains:

```
error while loading shared libraries: libopenslide.so.0: cannot open shared object file: No such file or directory```
 
I have tried to aclocal --force, libtoolize, autconf, automake and all the rest to see it picked ups the compiled library but no luck.

BTW, I've create my program inside the tools folder, not sure if this folder has special set of CFLAGS. I didn't see a -g flag being passed. 

I'm using the latest from master.

I've re-checkout the code few times and i get to the same point all the times. 

I'm not an expert in C my any means, so any help in the matter would be greatly appreciated.

Thanks for the support.

ade

**Comment by bgilbert** [comment]
If you're building your program using the OpenSlide build system and running it from inside the build directory, everything should just work, _if_ you're running it using the wrapper script generated by libtool.

Otherwise, `libopenslide.so.0` needs to be in your library search path.  Directories can be added to the search path permanently by adding them to `/etc/ld.so.conf` and running `ldconfig`, or temporarily (which would be better for your purposes) by adding the directory path to the `LD_LIBRARY_PATH` environment variable.  Note that the copy of `libopenslide.so.0` in the build tree will be in `src/.libs`.

**Comment by ade90036** [comment]
Ok, i can see the library being build and it correctly located in the ./src/.libs folder.
Let me add it to the ``` LD_LIBRARY_PATH ```

**Comment by ade90036** [comment]
IT WORKS .. thanks a million.

Would you mind this trick of adding the ``` libopenslide.so.0 ``` to ``` LD_LIBRARY_PATH ``` in the README.

I know that it may sound elementary to you but i'm sure other people found this helpfull..

Thanks again

ade

**Comment by ade90036** [comment]
can we update the readme with this info? i'm happy to close the issue.
