### ISSUE TITLE
Support for ICC profiles

### ISSUE THREAD

**Issue by j-hudecek** [openslide/openslide#237]
## Context

**Issue type**: Feature requests
**Operating system**: Any
**Platform**: Any
**OpenSlide version**: 
**Slide format**: SVS

## Details

It would be nice if OpenSlide applied embedded ICC profiles when reading slides. Aperio (and maybe others) include an ICC profile which could be read and applied using for example https://sourceforge.net/projects/sampleicc/ (public domain code, here is an example how to use it https://sourceforge.net/p/sampleicc/code/HEAD/tree/trunk/Tools/CmdLine/IccApplyProfiles/iccApplyProfiles.cpp) when reading regions from the file.

**Comment by bgilbert** [comment]
Thanks for writing this up.  However, I'm going to decline this request for now.  OpenSlide generally tries to return slide data with as little interpretation as possible, and also, applying ICC profiles requires additional complexity and additional context (such as the rendering intent and the ICC profile of the display/output device) that's best handled elsewhere.  Instead, OpenSlide 4.0 has new APIs for reading ICC profiles from the slide, and the application can apply those itself as part of its own workflow.
