### ISSUE TITLE
New, completly lost, I want to open in matlab WSI from a database..

### ISSUE THREAD

**Issue by WendyFloresFuentes** [openslide/openslide#239]
The distributor of the database recommended using openslide, I have tried to several ways and nothing work. I´m lost, where do I start?
I want to work with matlab.

**Comment by bgilbert** [comment]
We don't handle support requests in the OpenSlide issue tracker.  Please send your questions to the [openslide-users mailing list](https://lists.andrew.cmu.edu/mailman/listinfo/openslide-users/).
