### ISSUE TITLE
BUG: Incorrect use of memset

### ISSUE THREAD

**Issue by ade90036** [openslide/openslide#241]
## Context

**Issue type** : BUG 
**Operating system** : ALL 
**Platform** : ANY 
**OpenSlide version**: MASTER
**Slide format**: NA 

## Details
I'm using **openslide_read_region** in a multithreaded environment and i have noticed that the if you "underalllocate" the memory buffer in a repetitive rendering of variable window size it will cause some content from previous rendering to leak through.  

cairo tries to clear the window before paitning using CAIRO_OPERATOR_CLEAR, but that is not sufficient.

So openslide tries to recover from this by clearing the destination buffer before cairo begins its magic. 

Unfortunately the way that the buffer is "wiped" using memset is incorrect.

openslide.c:567
```c
  if (dest) {
    memset(dest, 0, w * h * 4);
}
```

memset takes a t_size which is length in bytes, therefore the size should be multiplied by (sizeof(uint32_t))

Regards

ade

**Comment by bgilbert** [comment]
`sizeof(uint32_t) == 4`, and indeed we're multiplying by 4.  I'm not sure I understand the problem you're having, though.  Is the buffer you're allocating smaller or larger than `w * h * sizeof(uint32_t)`?

**Comment by ade90036** [comment]
Pants... you stole my thunder... but you are absolutely right.

I'm using ```unsigned char``` pointer array in my code and i thought they were interchangeable (via observation, see code bellow).

To be honest i'm only getting the grips with C hence i'm not very familiar with the different primitives types.  But as you point out ```unsigned char``` is 1 byte and ```uint32_t``` is 4 bytes long and this is the source of my problems. 

How the heck is this working then?

Out of curiosity, what would be the value i need to put in the memset to clear out the buffer using a white color? 4294967295?

Apology again to have reported a phantom bug. 😸 

Regards

ade

**Comment by bgilbert** [comment]
The `uint32_t` value of white is `0xffffffff`.  OpenSlide's output format is [premultiplied ARGB](https://github.com/openslide/openslide/wiki/PremultipliedARGB), so the upper 8 bits of the `uint32_t` must be `0xff` to get a completely opaque pixel.

`memset`, though, works bytewise, and only cares about the lower 8 bits of its second argument.  So, in this case, you'd use `0xff`.
