### ISSUE TITLE
Objective-power missing in Philips tiff format

### ISSUE THREAD

**Issue by choosehappy** [openslide/openslide#243]
working with openslide 3.4.1, compiled recently from source, in python

I have a philips tiff file, and have attempted to read the "openslide.objective-power" property, which results in a "Mapping key not found" error.

Looking at the list of properties available in python, its obvious why the error is occurring, because the key is in fact missing : )

Openslide documentation says "openslide.objective-power: Magnification power of the objective. Often inaccurate; sometimes missing." 

I know philips is difficult to work with; just wanted to confirm that this is a known issue or a bug?

With a followup question of, do they  *really* not store the magnification in their headers? 

I pulled in the xml header and see:

                <Attribute Name="DICOM_DERIVATION_DESCRIPTION" Group="0x0008" Element="0x2111" PMSVR="IString">tiff-useBigTIFF=0-useRgb=0-levels=40,10002,10000,10001-processing=0-q80-sourceFilename=&quot;0a7326c7-20e0-424f-a519-afded3b287e7.isyntax&quot;;PHILIPS UFS V1.6.6495 | Quality=2 | DWT=1 | Compressor=16</Attribute>

where my slides were scanned at 40x, and i see levels="40", which may be the magnification? i don't have slides of a different magnification to confirm

**Comment by bgilbert** [comment]
In general, OpenSlide sets the objective-power property for any format where we know how to find the parameter.  With Philips TIFF, it wasn't clear how to get it.

You may be correct about the first item in the `levels=` list.  Most of my Philips TIFF slides have `40` there, and one slide has `20`.  If you could scan some slides with different objective powers and verify the value of that attribute, we can add it to the Philips TIFF driver.

**Comment by choosehappy** [comment]
quick update, having the lab scan a slide now at 5X, 10X, 20X, and 40X using a philips scanner.

Will report back findings when I get them

**Comment by choosehappy** [comment]
Fantastic news, that header information does line up with the magnification. 

I have 3 slides (B,C,D) scanned at 5x, 10x, 20x and 40x. the first integer after "levels" matches the magnification in all cases:

```
find . | sort -V |while read f
do
    echo $f
    openslide-show-properties "$f" | grep DICOM_DERIV
done


./Slide B at 5X.tiff
philips.DICOM_DERIVATION_DESCRIPTION: 'tiff-useBigTIFF=0-useRgb=0-levels=5,10002,10000,10001-processing=0-q80-sourceFilename="ffad2474-3752-4503-bd41-1fa41f1b4020.isyntax";PHILIPS UFS V1.6.6495 | Quality=2 | DWT=1 | Compressor=16'
./Slide B at 10X.tiff
philips.DICOM_DERIVATION_DESCRIPTION: 'tiff-useBigTIFF=0-useRgb=0-levels=10,10002,10000,10001-processing=0-q80-sourceFilename="ffad2474-3752-4503-bd41-1fa41f1b4020.isyntax";PHILIPS UFS V1.6.6495 | Quality=2 | DWT=1 | Compressor=16'
./Slide B at 20X.tiff
philips.DICOM_DERIVATION_DESCRIPTION: 'tiff-useBigTIFF=0-useRgb=0-levels=20,10002,10000,10001-processing=0-q80-sourceFilename="ffad2474-3752-4503-bd41-1fa41f1b4020.isyntax";PHILIPS UFS V1.6.6495 | Quality=2 | DWT=1 | Compressor=16'
./Slide B at 40X.tiff
philips.DICOM_DERIVATION_DESCRIPTION: 'tiff-useBigTIFF=0-useRgb=0-levels=40,10002,10000,10001-processing=0-q80-sourceFilename="ffad2474-3752-4503-bd41-1fa41f1b4020.isyntax";PHILIPS UFS V1.6.6495 | Quality=2 | DWT=1 | Compressor=16'
./Slide C at 5X.tiff
philips.DICOM_DERIVATION_DESCRIPTION: 'tiff-useBigTIFF=0-useRgb=0-levels=5,10002,10000,10001-processing=0-q80-sourceFilename="4620e5b9-e945-4d8b-acd5-4e88828c2a4a.isyntax";PHILIPS UFS V1.6.6495 | Quality=2 | DWT=1 | Compressor=16'
./Slide C at 10X.tiff
philips.DICOM_DERIVATION_DESCRIPTION: 'tiff-useBigTIFF=0-useRgb=0-levels=10,10002,10000,10001-processing=0-q80-sourceFilename="4620e5b9-e945-4d8b-acd5-4e88828c2a4a.isyntax";PHILIPS UFS V1.6.6495 | Quality=2 | DWT=1 | Compressor=16'
./Slide C at 20X.tiff
philips.DICOM_DERIVATION_DESCRIPTION: 'tiff-useBigTIFF=0-useRgb=0-levels=20,10002,10000,10001-processing=0-q80-sourceFilename="4620e5b9-e945-4d8b-acd5-4e88828c2a4a.isyntax";PHILIPS UFS V1.6.6495 | Quality=2 | DWT=1 | Compressor=16'
./Slide C at 40X.tiff
philips.DICOM_DERIVATION_DESCRIPTION: 'tiff-useBigTIFF=0-useRgb=0-levels=40,10002,10000,10001-processing=0-q80-sourceFilename="4620e5b9-e945-4d8b-acd5-4e88828c2a4a.isyntax";PHILIPS UFS V1.6.6495 | Quality=2 | DWT=1 | Compressor=16'
./Slide D at 5X.tiff
philips.DICOM_DERIVATION_DESCRIPTION: 'tiff-useBigTIFF=0-useRgb=0-levels=5,10002,10000,10001-processing=0-q80-sourceFilename="b8bdaa8a-5786-4231-a53d-c173e52af187.isyntax";PHILIPS UFS V1.6.6495 | Quality=2 | DWT=1 | Compressor=16'
./Slide D at 10X.tiff
philips.DICOM_DERIVATION_DESCRIPTION: 'tiff-useBigTIFF=0-useRgb=0-levels=10,10002,10000,10001-processing=0-q80-sourceFilename="b8bdaa8a-5786-4231-a53d-c173e52af187.isyntax";PHILIPS UFS V1.6.6495 | Quality=2 | DWT=1 | Compressor=16'
./Slide D at 20X.tiff
philips.DICOM_DERIVATION_DESCRIPTION: 'tiff-useBigTIFF=0-useRgb=0-levels=20,10002,10000,10001-processing=0-q80-sourceFilename="b8bdaa8a-5786-4231-a53d-c173e52af187.isyntax";PHILIPS UFS V1.6.6495 | Quality=2 | DWT=1 | Compressor=16'
./Slide D at 40X.tiff
philips.DICOM_DERIVATION_DESCRIPTION: 'tiff-useBigTIFF=0-useRgb=0-levels=40,10002,10000,10001-processing=0-q80-sourceFilename="b8bdaa8a-5786-4231-a53d-c173e52af187.isyntax";PHILIPS UFS V1.6.6495 | Quality=2 | DWT=1 | Compressor=16'
```
What do you think? Can it be added to openslide as discussed above?

I can make the slides available should you need.

**Comment by bgilbert** [comment]
I've just added some [public Philips TIFF slides](https://openslide.cs.cmu.edu/download/openslide-testdata/Philips-TIFF/) to openslide-testdata.  Unfortunately, the rule does not hold for those slides:

```
philips.DICOM_DERIVATION_DESCRIPTION: 'tiff-useBigTIFF=1-useRgb=0-levels=10003,10002,10000,10001-processing=0-q80-sourceFilename="T14-03469_3311940 - 2015-12-09 17.29.29.ndpi"'
```

In principle we could ignore the first number if it's larger than a threshold.
