### ISSUE TITLE
opendlide causes caffe to crash

### ISSUE THREAD

**Issue by ihuale** [openslide/openslide#245]
## Context
hello, I found an error when I was using openslide and caffe.
I tried to put caffe in my program，my program uses openslide to read images and display them. 
I compiled caffe correctly and put the classification.cpp in my program(remove the main function), and then my program was successfully compiled, but when I try to start the program it failed to start and with the messages:
![image](https://user-images.githubusercontent.com/18436096/42681023-2684fc06-86b9-11e8-86df-6cf1943a046b.png)
it means: 
Unable to locate program input point openslide_close on dynamic link library MPI.exe

and the console output:
![image](https://user-images.githubusercontent.com/18436096/42681063-439b9f34-86b9-11e8-997d-9cb5a02fa712.png)
the bottom fivelines it means: 
Exception thrown at 0x00007FFC6B769968(ntdll.dll): 0xc0000139: Entry Point Not Found.
Thread 0x13f0 has exited, return value is -1073741511 (0xc0000139).
Thread 0x35cc has exited, return value is -1073741511 (0xc0000139).
Thread 0x45ec has exited, return value is -1073741511 (0xc0000139).
Program"[11996]MPI.exe " has exited, return value is -1073741511 (0xc0000139) 'Entry Point Not Found'.

**Issue type** (bug report or feature request): bug report
**Operating system** (e.g. Fedora 24, Mac OS 10.11, Windows 10): win10
**Platform** (e.g. 64-bit x86, 32-bit ARM): 64-bit
**OpenSlide version**: 3.4.1 and 3.4.0
**Slide format** (e.g. SVS, NDPI, MRXS): MRXS

### Steps to reproduce
1.Put cafffe and openslide in the same project and configure them correctly
2.Use the api provided by openslide,  e.g. : “openslide_detect_vendor()”
3.successfully compiled
4.run output.exe

### Tried solutions
I tried the following methods:
(1)use the release version you and caffe provided and it was configured correctly, but still the same error.

(2)creat a new project, write a sample api from opensilde it run successed, and then I put the classification.cpp into it and configure it correctly but still the same error.

(3)creat a new project, put the classification.cpp into it and successfully ran it. and then add openslide and write a sample api from opensilde, successfully compiled it, but still the same error......

(4)reapt abrove steps on vs2013, failed again......

(5)used the another computer to reapt abrove steps,but it still the same error.....

(6)changed the openslide and failed again......

**Comment by bgilbert** [comment]
Does caffe include different versions of the libraries that are bundled with OpenSlide?

**Comment by ihuale** [comment]
I checked the include folder of caffe, it does not contain opeslide.
If you have more ways to solve the problem, please reply me.
thanks！

**Comment by bgilbert** [comment]
The question was whether caffe includes some of the libraries that OpenSlide depends on.

**Comment by ihuale** [comment]
These are the libraries of caffe's include：
boost，gflags, glog. hdf5, leveldb. lmdb, nccl, openblas. opencv. protobuf, cuda, cudnn

**Comment by bgilbert** [comment]
HDF5, at least, requires zlib.  Others of those libraries, such as OpenCV, may also have transitive dependencies on libraries required by OpenSlide.  If you try to load multiple versions of the same library into a process, you can encounter errors like this.  The fix is to compile all of your libraries with a consistent set of dependencies.

**Comment by ihuale** [comment]
ok, thank you very much ^_^
