### ISSUE TITLE
Dead link for Aperio vendor documentation

### ISSUE THREAD

**Issue by markemus** [openslide/openslide#250]
## Context

**Issue type** (bug report or feature request): 
Bug report.
**Operating system** (e.g. Fedora 24, Mac OS 10.11, Windows 10): 
**Platform** (e.g. 64-bit x86, 32-bit ARM): 
**OpenSlide version**: 
**Slide format** (e.g. SVS, NDPI, MRXS): 
SVS, Tiff

## Details

https://openslide.org/formats/aperio/#vendor-documentation

The link for the Aperio vendor documentation no longer works. Does anyone know if it's hosted somewhere new? I searched around online but haven't been able to find it.

**Comment by bgilbert** [comment]
As far as I know, Leica has not taken over hosting of this documentation, though I haven't checked in a while.  The dead link is intentionally being left on the OpenSlide website for historical purposes.
