### ISSUE TITLE
 Mrxs Error: Cannot read slide position info: Expected 1 value

### ISSUE THREAD

**Issue by jetic83** [openslide/openslide#251]
## Context

**Issue type** (bug report or feature request): bug report
**Operating system** (e.g. Fedora 24, Mac OS 10.11, Windows 10): Win 7
**Platform** (e.g. 64-bit x86, 32-bit ARM): 64-bit
**OpenSlide version**: 3.4.1
**Slide format** (e.g. SVS, NDPI, MRXS): MRXS

## Details
When using openslide-show-properties.exe, I get an error with certain (not all) .mrxs files:

`Cannot read slide position info: Expected 1 value`

However, ImageScope and CaseViewer can open those files without problems.

**Comment by 0x001B** [comment]
## Context

**Operating system** (e.g. Fedora 24, Mac OS 10.11, Windows 10): RHEL 7
**Platform** (e.g. 64-bit x86, 32-bit ARM): 64-bit
**OpenSlide version**: 3.4.1
**Slide format** (e.g. SVS, NDPI, MRXS): MRXS

## Details

I get exactly the same error with Openslide 3.4.1 on a RHEL 7 system for certain (not all) .mrxs files.

Any news on this issue?

**Comment by Evizero** [comment]
I also see the same error for a couple of slides

**Comment by cett01** [comment]
I saw the same error for a couple of slides, on  version 3.4.1. CaseViewer can open this slides and zoom perfectly to level 0. I can share this slides with you.
`java.io.IOException: Cannot read slide position info: Expected 1 value
	at org.openslide.OpenSlide.checkError(OpenSlide.java:178)
	at org.openslide.OpenSlide.<init>(OpenSlide.java:114)
`

**Comment by mjkvaak** [comment]
I was able to solve this problem with Slide Converter provided by 3D Histec in their webpage: https://www.3dhistech.com/software-downloads. Simply convert from mrxs to mrxs after which openslide can open the images. I will report, if I can find some differences between the original and the converted files.

**Comment by skrackow** [comment]
The difference is that the conversion removes the overlap of camera images.

**Comment by iowatom** [comment]
I am having the same issue with a very few mrxs file having the "Expected 1 value" when I try to extract to a .dz file. 
I am not understanding how or whether this can be solved from these comments. Any clarification would be appreciated.

**Comment by iowatom** [comment]
Apparently we switched to a new scanner from 3Dhistech using 3.2.0, Build 146673 software earlier this year. That is when this issue showed itself. It would seem that some change has been made to the mrxs format that openslide cannot use.
Those potential fixes dealt with earlier versions?

**Comment by nunocalaim** [comment]
Is there anything preventing solving this issue with the merge of the fix proposed by the company that produces mrxs files?

**Comment by jjhbw** [comment]
Our lab is having the same problem. We're planning to try to convert our mrxs files with SlideMaster as a bandaid, but ideally this would be fixed in OpenSlide. AFAIK 3Dhistech contributed a patch in #333, but they did not really document the rationale behind it so the PR is still open.

**Comment by GSz-3DH** [comment]
Dear All,

MRXS to MRXS conversion is not just a bandaid, but the solution for You.

There are a few more things happening during the mrxs to mrxs conversion:
auto color adjustment for FL slides,
bilinear filter for smoothing,
pixel filter for smoothing,
intensity stitching to make overall intensity balanced,
stitching filter to smooth stitched edges,
optimize to slow connection is basically recompressing the image in jpg80, which can also smooth the image.
And maybe that's not all, I'm not sure.
We have these filters built-in to our viewers, that is why an overlapped mrxs image has problems in all alternative viewers.

I guess openslide will not do the above image manipulation ever.

So, the solution is to do mrxs to mrxs conversion, and use de-everlapped images.
The conversion may be applied during scanning.
local scanning DX software>Turn on: Change file format (MRXS)
server scanning DX software>Turn on: Apply slide processing (MRXS)
The RX and the P1000 has similar options.

And You can always use the folder watch feature of SlideMaster, and convert the scanned slides automatically.
This works with any 3dh scanner version.

Kind regards,

**Comment by bgilbert** [comment]
If anyone can contribute a sample slide affected by this problem, please [upload it here](https://docs.google.com/forms/d/e/1FAIpQLSf4RsqIEVqB_FlY0mJtmi9fhHNSqc_59e4uHIoAgtkbtplH0w/formResponse).  If you can authorize us to redistribute the sample in [openslide-testdata](https://openslide.cs.cmu.edu/download/openslide-testdata/) under the [Creative Commons Zero](https://creativecommons.org/public-domain/cc0/) license, that'd be especially helpful!

**Comment by jjhbw** [comment]
@bgilbert I just uploaded an example .mrxs WSI from our lab that should enable you to reproduce the problem described in this issue. Couldn't find one smaller than 2GB, sorry. Feel free to contact me if you need any more info!

**Comment by bgilbert** [comment]
@jjhbw Awesome, thanks for the sample!  The tar archive decodes correctly, but appears to be missing `Data0001.dat` and `Data0002.dat`.  Could you upload those files as well?

**Comment by jjhbw** [comment]
@bgilbert sorry for that... It appears we're missing those files locally as well, sloppy... I'll take another look at the archive to see if I can get you a copy of the complete slide.

I was able to reproduce this issue (`Cannot read slide position info: Expected 1 value`) with this incomplete slide, too, by the way.

**Comment by bgilbert** [comment]
Thanks!  Yup, it reproduces as-is, but I'd like to make sure the slide reads correctly with the issue fixed.  It's currently missing a pyramid level.

**Comment by bgilbert** [comment]
Thanks for reporting this, all.  #521 should fix it.

@jjhbw, I was able to work around the missing pyramid level when testing, but am still interested in a complete sample if you have one.  If it's too difficult to fix the first slide, a different one would also work.  Thanks for the help!

**Comment by mrymsadeghi** [comment]
I have the same problem but my slide is not missing Data0001.dat and Data0002.dat files. I uploaded it for the reporoducibility. Would you please check it?
python 3.10.11
openslide 1.3.0

**Comment by bgilbert** [comment]
@mrymsadeghi We haven't received your slide.  It's possible that you didn't finish the form submission.  (The form has two pages.)

Double-check that you're using OpenSlide 4.0.0, not 3.4.1.  If so, please open a new bug with the details of your problem.
