### ISSUE TITLE
After extract a region of svs file. Can openslide save it as svs format?

### ISSUE THREAD

**Issue by hongyiyu** [openslide/openslide#254]
After extract a region of svs file. I want to save it as .svs format.
However, It seems there is no function in openslide for write. only read function.
Is there any way that I can save the extracted region in svs format?

Thanks in advance.

**Comment by bgilbert** [comment]
Not with OpenSlide.  OpenSlide is a read-only library and intentionally provides no way to modify whole-slide image files.
