### ISSUE TITLE
Error reading files in path with non-ASCII characters

### ISSUE THREAD

**Issue by hillin** [openslide/openslide#259]
## Context

**Issue type**: bug report
**Operating system**: Windows 10
**Platform**: 64-bit x86
**OpenSlide version**: 3.4.1
**Slide format**: MRXS

## Details

If the slide file is placed in a directory whose path contains non-ASCII characters, the file will fail to load, and `openslide_get_error()` will complain about cannot find the Slidedat.ini file.

**Comment by bgilbert** [comment]
You can get development builds [here](https://buildbot.openslide.org/snapshots/windows/).

**Comment by hillin** [comment]
Thanks Benjamin! I tried the latest development build (on 2018-06-18), the problem still persists. Unfortunately I can't get my hand on building from the master source, I'll try it as soon as I can.
