### ISSUE TITLE
How to find the pixel width in images?

### ISSUE THREAD

**Issue by RJain12** [openslide/openslide#261]
How do I find the pixel width in an SVS image? (This pixel width will be in mm, e.g. 0.7)

**Comment by bgilbert** [comment]
See the [`openslide.mpp-{x,y}` properties](https://openslide.org/docs/properties/).

We don't handle support requests in the OpenSlide issue tracker.  Please send your questions to the [openslide-users mailing list](https://lists.andrew.cmu.edu/mailman/listinfo/openslide-users/).
