### ISSUE TITLE
unregular install trouble with openjpeg

### ISSUE THREAD

**Issue by yasohasakii** [openslide/openslide#277]
## Context

**Issue type** (bug report or feature request): bug report
**Operating system** (e.g. Fedora 24, Mac OS 10.11, Windows 10):CentOS 
**Platform** (e.g. 64-bit x86, 32-bit ARM): 64-bit
**OpenSlide version**: 3.4.1
**Slide format** (e.g. SVS, NDPI, MRXS): 

## Details
hi! I have installed openjpeg(2.3) in my costom path without any problem , when I configure openslide like `./configure -prefix=/home/caibojun/lib/openslide LDFLAGS=-L/home/caibojun/lib/openjpeg/lib CPPFLAGE=-I/home/caibojun/lib/openjpeg/include` I got failed infomation as below:  
>checking for OPENJPEG2... no  
>checking for OPENJPEG... no  
>checking for OpenJPEG (fallback)... configure: error: in '/home/caibojun/lib/openslide-3.4.1':
configure: error: cannot find OpenJPEG  
>See 'config.log' for more details  
Still don't kown how to fix it, please offer some advice if you are avilable, thanks!

**Comment by valuat** [comment]
I'm having the same problem. What was the solution?
