### ISSUE TITLE
openslide wrong jpeg library version library is 62, caller expects 80

### ISSUE THREAD

**Issue by Nandayang** [openslide/openslide#279]
## Context

**Issue type** (bug report or feature request):  bug report
**Operating system** (Ubuntu 16.04.2 LTS): 
**Platform** (e.g. x86_64): 
**OpenSlide version**: 3.4.1
**Slide format** (e.g. SVS, NDPI, MRXS): SVS

## Details
After using read_region,  i got an all zero matrix, then i check the error code and it returned as bellow: openslide wrong jpeg library version library is 62, caller expects 80
i thought it was caused by the version of jpeg library, however i went to /usr/local/lib/ and using objdump to checkout my version ,and it showed that there was no 6.2 jpeg version on my system. 

Could you plz help me to find what happened?

**Comment by bgilbert** [comment]
You're using an OpenSlide binary compiled for one version of libjpeg, but your system has a different version of libjpeg.  Be sure to compile OpenSlide for the version of libjpeg installed on your system.
