### ISSUE TITLE
how to update openslide to 3.4.1?

### ISSUE THREAD

**Issue by w867066886** [openslide/openslide#282]
## Context
im using openslide3.4.0  and i meet a error 
"openslide.lowlevel.OpenSlideError : TIFFRGBAImageGet fail"
There is an answer saying that i need to update openslide to 3.4.1
when  i use "sudo apt-get purge --auto-remove python-openslide",i cannot delete it 
So how can i update openslide to 3.4.1?

**Comment by bgilbert** [comment]
If you're using an older Linux distribution that only packages OpenSlide 3.4.0, then you might try compiling OpenSlide from source code.  OpenSlide 3.4.1 source is available from the [download page](https://openslide.org/download/).
