### ISSUE TITLE
How to convert png into svs

### ISSUE THREAD

**Issue by yasohasakii** [openslide/openslide#283]
## Context

**Issue type** (bug report or feature request): feature request

**Operating system** (e.g. Fedora 24, Mac OS 10.11, Windows 10): 
**Platform** (e.g. 64-bit x86, 32-bit ARM): 
**OpenSlide version**: 
**Slide format** (e.g. SVS, NDPI, MRXS): 

## Details
Hi ,is there any api can convert processed png files into svs again?

**Comment by bgilbert** [comment]
Nope.  By design, OpenSlide can only read whole-slide image files, not write them.
