### ISSUE TITLE
configure: error: cannot find OpenJPEG

### ISSUE THREAD

**Issue by ynulonger** [openslide/openslide#284]
## Context

**Issue type** (bug report or feature request): Building error
**Operating system** (e.g. Fedora 24, Mac OS 10.11, Windows 10): Red Hat Enterprise Linux Server release 7.4 (Maipo)
**Platform** (e.g. 64-bit x86, 32-bit ARM): x86_64
**OpenSlide version**: OpenSlide 3.4.1
**Slide format** (e.g. SVS, NDPI, MRXS): SVS

## Details
Hi, I downloaded the openslide-3.4.1.tar.gz from `https://openslide.org/download/` and try to bulid it on RedHat system, but when I run ./configure, it raised this error:
**checking for OpenJPEG (fallback)... configure: error: in `/scratch/yy3u19/openslide-3.4.1':
configure: error: cannot find OpenJPEG**
So, could you please tell me how to fix it?

**Comment by bgilbert** [comment]
Run `yum install openjpeg-devel`.
