### ISSUE TITLE
Image distorted by patches repeating in QuPath

### ISSUE THREAD

**Issue by michaelmooreny** [openslide/openslide#285]
## Context

**Issue type** (bug report or feature request): bug report
**Operating system** (e.g. Fedora 24, Mac OS 10.11, Windows 10): ubuntu 16.04
**Platform** (e.g. 64-bit x86, 32-bit ARM): 
**OpenSlide version**: 3.4.1
**Slide format** (e.g. SVS, NDPI, MRXS): .tif (converted from ndpi)

## Details

QuPath is a digital pathology image processing software many of you may be familiar with. I recently reported a bug in QuPath and was referred to post here https://github.com/qupath/qupath/issues/386https://github.com/qupath/qupath/issues/386. The problem I seem to be having with the openslide image library is that opening images seems to be distorting them in such a way that they are being cut into patches and repeated and moved around the window. This is specifically happening with.tif images which were converted from .ndpi files. Please let me know if there is any other information I can provide to help you in solving this problem. All of the other relevant background for this problem is included in the link to the bug report above.

**Comment by Tkilvaer** [comment]
Hi
I had this problem with MRXS files. Downgrading libpixman-1-0 and libpixman-1-dev to vs. 0.33.6-1. fixed this issue for me on ubunutu 19.10

**Comment by bgilbert** [comment]
This is likely https://github.com/openslide/openslide/issues/278.  I'll go ahead and close, but if you're still seeing this with pixman newer than 0.38.x, feel free to follow up here.
