### ISSUE TITLE
Clarify support status of OpenSlide on openslide.org

### ISSUE THREAD

**Issue by adamu** [openslide/openslide#296]
* The last [mailing list announcement](https://lists.andrew.cmu.edu/pipermail/openslide-announce/) was November 2017
* The [last commit](https://github.com/openslide/openslide/commits/master) was in May 2018
* None of the pull requests have received any interaction from a member of this project since around that time.

**Comment by agoode** [comment]
You can check the openslide-users mailing list, but this is currently the most accurate summary of the situation:
https://lists.andrew.cmu.edu/pipermail/openslide-users/2019-March/001522.html

I will leave this issue open as documentation.

**Comment by Racater** [comment]
any suggested alternative?

**Comment by bgilbert** [comment]
[OpenSlide 4.0.0](https://github.com/openslide/openslide/releases/tag/v4.0.0) has been released and maintenance is ongoing, so I'll close this out.
