### ISSUE TITLE
configure: error: cannot find OpenJPEG - macos 10.14.6

### ISSUE THREAD

**Issue by valuat** [openslide/openslide#298]
## Context

Can't build openslide.

**Issue type** (bug report or feature request): bug report
**Operating system** (e.g. Fedora 24, Mac OS 10.11, Windows 10): macos 10.14.6
**Platform** (e.g. 64-bit x86, 32-bit ARM): 64-bit x86
**OpenSlide version**: 3.4.1
**Slide format** (e.g. SVS, NDPI, MRXS): 

## Details
As many have already brought this problem up in different shapes and forms, I can't build openslide for macos. I've installed all required libraries and ran ./configure with the following options (with the proper location of the openjpeg header and library files).

./configure CPPFLAGS=-I/usr/local/include/openjpeg-2.3 LDFLAGS=-L/usr/local/lib

I'd appreciate any help as homebrew is not an option at this time. Thanks!

**Comment by bgilbert** [comment]
This ticket is fairly old, so I'll close it as stale.  If you or someone else is still having this issue, please open a new issue with a build log so the problem can be diagnosed.
