### ISSUE TITLE
Error installing openslide on linux os

### ISSUE THREAD

**Issue by shahto** [openslide/openslide#299]
"./configure" runs successfully but "make" gives me these errors

CC       src/src_libopenslide_la-openslide.lo
pgcc-Error-Unknown switch: -pedantic
pgcc-Error-Unknown switch: -pthread
pgcc-Error-Unknown switch: -pthread
pgcc-Error-Unknown switch: -Wall
pgcc-Error-Unknown switch: -Wextra
pgcc-Error-Unknown switch: -Wstrict-prototypes
pgcc-Error-Unknown switch: -Wmissing-prototypes
pgcc-Error-Unknown switch: -Wmissing-declarations
pgcc-Error-Unknown switch: -Wnested-externs
pgcc-Error-Unknown switch: -fno-common
make[1]: *** [src/src_libopenslide_la-openslide.lo] Error 1
make[1]: Leaving directory `/home/mydir/dataprocessing/'
make: *** [all] Error 2

I do not have root access and cannot install anything on \user\bin\local

**Comment by bgilbert** [comment]
You appear to be using a compiler that doesn't support common compiler options.  GCC will work; clang should also work.  Try passing `CC=gcc` to `./configure`.
