### ISSUE TITLE
BIF file : Bad direction attribute "LEFT"

### ISSUE THREAD

**Issue by ylaizet** [openslide/openslide#303]
## Context

**Issue type** (bug report or feature request): bug report
**Operating system** (e.g. Fedora 24, Mac OS 10.11, Windows 10): Ubuntu 16.04
**Platform** (e.g. 64-bit x86, 32-bit ARM): 64-bit x86
**OpenSlide Python version** (`openslide.__version__`): 1.1.1
**OpenSlide version** (`openslide.__library_version__`): 3.4.0-1build1
**Slide format** (e.g. SVS, NDPI, MRXS): bif

## Details

I use openslide-python successfully to view ndpi files, then I tried to view .bif slides but I get an error:

`Bad direction attribute "LEFT"`

I can open my bif file with a slide viewer but not with openslide. If I use the example os-2bif file, openslide works so I guess that my bif file may have special attribute specification not supported in openslide.

Thanks for help

## EDIT:

I tried to dig into the error and I came up with the following:
The error is raised in the [openslide-vendor-ventana.c file line 589](https://github.com/openslide/openslide/blob/7b99a8604f38280d14a34db6bda7a916563f96e1/src/openslide-vendor-ventana.c#L590) where the value of the direction variable is obviously set to "LEFT" in my .bif file. It seems that this value is not supported (the reason in unknown to me, wether my file is no properly formatted or if LEFT is a missing value here?).
At the top of the file, I see only "RIGHT" and "UP" constant values declared but no "LEFT", which ends to the encountered error. Does anybody have enough experience with the .bif format specification or openslide lib code to give an hint to fix this?
Thanks

**Comment by bgilbert** [comment]
Duplicate of #234.
