### ISSUE TITLE
Fails to extract regions from Mirax image

### ISSUE THREAD

**Issue by tvngithub** [openslide/openslide#314]
## Context

**Issue type** (bug report or feature request): bug report
**Operating system** (e.g. Fedora 24, Mac OS 10.11, Windows 10):  all
**Platform** (e.g. 64-bit x86, 32-bit ARM): all
**OpenSlide version**: 3.4.1 and newer
**Slide format** (e.g. SVS, NDPI, MRXS): MRXS

## Details
openslide-write-png fails to extract some regions on some MRXS image. The attached test image example can be viewed perfectly with 3DHistech Viewer but regions are not extracted correctly using openslide-write-png. There is no error issued but the resulting png image is empty (filled with 0) when the region x=53000 y=55747 level=0 width=1024 height=786 is extracted using openslide-write-png from the attached test case.
The problem exist only with some MRXS files and in some regions.

**Comment by tvngithub** [comment]
Test case can be downloaded from
https://1drv.ms/u/s!Ao8q3q6iWbR0hlf1byoUIj8HeE3C

**Comment by bgilbert** [comment]
You're getting an empty PNG because there are no pixels at that location.  OpenSlide uses the coordinate system of the underlying slide file, and in this case, the pixels start at (15756, 81211):

```shell
$ openslide-show-properties TestSlide_OpenSlide_Extract_Region.mrxs | grep bounds
openslide.bounds-height: '92154'
openslide.bounds-width: '65550'
openslide.bounds-x: '15756'
openslide.bounds-y: '81211'
```

Adding those offsets, we get:
```
$ openslide-write-png TestSlide_OpenSlide_Extract_Region.mrxs 68756 136958 0 1024 786 out.png
```
![out.png](https://user-images.githubusercontent.com/361374/96222111-a7674100-0f59-11eb-8586-1e550ee88060.png)
