### ISSUE TITLE
Permission to show names interferes with displaying voting buttons of delegated votes

### ISSUE THREAD

**Issue by tibetischeszentrum** [openslide/openslide#319]
## Context

**Issue type** (bug report or feature request): bug report
**Operating system** (e.g. Fedora 24, Mac OS 10.11, Windows 10): Windows 10
**Platform** (e.g. 64-bit x86, 32-bit ARM): 64-bit
**OpenSlide version**:  3.3

## Details
OpenSlides does not show voting buttons for delegated votes, when the delegates group does not have the permission to show names of other participants in the participants list. 
Therefore it is not possible to not display the list of all members that have been entered into openslides and still have delegated votes. This connection is also not at all obvious, since there is no warning or error message; the voting buttons will just silently not show op for the delegated votes. 
This is probably not intended. The permission to show the names should not interfere with the voting process.

**Comment by jaharkes** [comment]
Wrong project. I assume you are looking for https://github.com/OpenSlides/OpenSlides
