### ISSUE TITLE
C++ openslide_read_region parallel with OpenMP?

### ISSUE THREAD

**Issue by Alfons0329** [openslide/openslide#321]
## Context

**Issue type** (bug report or feature request): 
**Operating system** Ubuntu 18.04.5 LTSD
**Platform** Intel x86-64
**OpenSlide version**: 3.4.1
**Slide format** SVS

## Details
I am using openslide to read slide from [GDC Cancer Portal](https://portal.gdc.cancer.gov/repository?facetTab=files&filters=%7B%22op%22%3A%22and%22%2C%22content%22%3A%5B%7B%22op%22%3A%22in%22%2C%22content%22%3A%7B%22field%22%3A%22cases.project.project_id%22%2C%22value%22%3A%5B%22TCGA-LUSC%22%5D%7D%7D%2C%7B%22op%22%3A%22in%22%2C%22content%22%3A%7B%22field%22%3A%22files.experimental_strategy%22%2C%22value%22%3A%5B%22Diagnostic%20Slide%22%5D%7D%7D%5D%7D&searchTableTab=files)
with large svs files.

I found that directly read SVS file is slow, hence I decided to combine OpenMP with it.
From
```cpp
openslide_read_region(slide, buf, 0, 0, target_level, target_width, target_height);
```
to
```cpp
const uint32_t chunksize = target_width * target_height / thr;
  const uint32_t segment_y = target_height / thr;
  #pragma omp parallel for num_threads(thr)
  for(int i = 0; i < (int)thr; i++){
      if(i == thr - 1){
          openslide_read_region(slide, buf + chunksize * i, 0, 4 * segment_y * i, target_level, target_width, target_height  - segment_y);
      }
      else{
          openslide_read_region(slide, buf + chunksize * i, 0, 4 * segment_y * i, target_level, target_width, segment_y);
      }
  }
```

This generated desired result (convert and imwrite with openCV) with left being serial version and right parallel one as shown below
![image](https://user-images.githubusercontent.com/22470089/103614967-b102b280-4f64-11eb-8697-f6008e931507.png)

But there are two problems I found

* First, if compare the original ARGB buffer with the parallel one, they will have 3% difference, but unnoticeable to eye.
* Second, if the thread for OpenMP is not the divisor of the slide height in level 1, then the result image will be like a shattered slide scan.
![image](https://user-images.githubusercontent.com/22470089/103615216-24a4bf80-4f65-11eb-8d34-b11fec3fa2af.png)

Thank you very much for the help!

**Comment by noobOriented** [comment]
you should change this line:
`const uint32_t chunksize = target_width * target_height / thr;`
to
`const uint32_t chunksize = target_width * (target_height / thr);`

the missing parenthesis makes `chunk_size` not divided by `target_width`
thus pointers passed to `openslide_read_region` in threads with `i > 0` are mis-aligned with the start of rows

**Comment by bgilbert** [comment]
Looks like this was addressed, so I'll close.
