### ISSUE TITLE
Can SVS format be sliced into multiple JPG files?

### ISSUE THREAD

**Issue by bbhxwl** [openslide/openslide#322]
Can SVS format be sliced into multiple JPG files?

**Comment by bgilbert** [comment]
Yes.  Read the desired regions from the slide file, then write the pixel data for each region to a JPEG.

**Comment by bbhxwl** [comment]
> Yes. Read the desired regions from the slide file, then write the pixel data for each region to a JPEG.

I want to get a case, because my English is not good, and I use C#

![image](https://user-images.githubusercontent.com/26525599/111401813-fa117880-8704-11eb-9710-91fae27b1b07.png)

**Comment by Abhinav-Telukunta** [comment]
> Yes. Read the desired regions from the slide file, then write the pixel data for each region to a JPEG.

@bgilbert What is the function to be used in C to write to a file?
