### ISSUE TITLE
Unable to read file?

### ISSUE THREAD

**Issue by bbhxwl** [openslide/openslide#323]
Unable to read file?

My file is TIFF and SVS have been tested and cannot be read

**Comment by bgilbert** [comment]
This is an issue tracker, not a support forum.  Please try the openslide-users mailing list, bearing in mind that you'll need to provide much more information for anyone to be able to help you.

**Comment by bbhxwl** [comment]
> This is an issue tracker, not a support forum. Please try the openslide-users mailing list, bearing in mind that you'll need to provide much more information for anyone to be able to help you.

Sorry, my English is not good, it's Chinese, it's for you openslide-users@lists.andrew.cmu.edu Does this email send a message?

**Comment by bbhxwl** [comment]
Hope to help me, I downloaded the binary file, set the environment variables, but still can't read the SVS file.

**Comment by bbhxwl** [comment]
> This is an issue tracker, not a support forum. Please try the openslide-users mailing list, bearing in mind that you'll need to provide much more information for anyone to be able to help you.

hello
