### ISSUE TITLE
OSError: -9: Can I get more explanation why it occurs and how to resolve 

### ISSUE THREAD

**Issue by haseeb33** [openslide/openslide#324]
## Error explanation request

**Issue type** => bug type
**Operating system** => Linux 
**OpenSlide version** => 1.1.2 
**Slide format** => NDPI

## I am working with pathology slide images(.ndpi format) and I got this error.

    import openslide
    from PIL import ImageFile,Image 
    Image.MAX_IMAGE_PIXELS = None
    im = openslide.ImageSlide('ABCD.ndpi')
    print(im.level_dimensions[0])          #image size is (90112, 52224)
    im.get_thumbnail((901,522))

> ---------------------------------------------------------------------------
> OSError                                   Traceback (most recent call last)
> <ipython-input-12-381a3dba2608> in <module>
> ----> 1 im.get_thumbnail((901,522))
> 
> /usr/local/lib/python3.6/dist-packages/openslide/__init__.py in get_thumbnail(self, size)
>     132                 zip(self.dimensions, size)])
>     133         level = self.get_best_level_for_downsample(downsample)
> --> 134         tile = self.read_region((0, 0), level, self.level_dimensions[level])
>     135         # Apply on solid background
>     136         bg_color = '#' + self.properties.get(PROPERTY_NAME_BACKGROUND_COLOR,
> 
> /usr/local/lib/python3.6/dist-packages/openslide/__init__.py in read_region(self, location, level, size)
>     373             # PIL thinks the bottom right is the first *excluded* pixel
>     374             crop = self._image.crop(image_topleft +
> --> 375                     [d + 1 for d in image_bottomright])
>     376             tile_offset = tuple(il - l for il, l in
>     377                     zip(image_topleft, location))
> 
> /usr/local/lib/python3.6/dist-packages/PIL/Image.py in crop(self, box)
>    1134             return self.copy()
>    1135 
> -> 1136         self.load()
>    1137         return self._new(self._crop(self.im, box))
>    1138 
> 
> /usr/local/lib/python3.6/dist-packages/PIL/TiffImagePlugin.py in load(self)
>    1055     def load(self):
>    1056         if self.tile and self.use_load_libtiff:
> -> 1057             return self._load_libtiff()
>    1058         return super().load()
>    1059 
> 
> /usr/local/lib/python3.6/dist-packages/PIL/TiffImagePlugin.py in _load_libtiff(self)
>    1159 
>    1160         if err < 0:
> -> 1161             raise OSError(err)
>    1162 
>    1163         return Image.Image.load(self)
> 
> OSError:  -9

Any direction to resolve or understand this issue would be highly appreciated.

**Comment by haseeb33** [comment]
@bgilbert But I can't open **.ndpi** slide using ```openslide.OpenSlide``` because the format is not supported.

    im = openslide.OpenSlide('ABCD.ndpi')

> OpenSlideUnsupportedFormatError: Unsupported or missing image file

**Comment by bgilbert** [comment]
I'd recommend opening your slide file with software that knows how to read it.  OpenSlide is not actively maintained, and its NDPI support is unlikely to improve in the near future.
