### ISSUE TITLE
make install command says no rule to make target 'install'

### ISSUE THREAD

**Issue by Abhinav-Telukunta** [openslide/openslide#325]
## Context

**Issue type** (bug report or feature request): bug report
**Operating system** (e.g. Fedora 24, Mac OS 10.11, Windows 10): Ubuntu 
**Platform** (e.g. 64-bit x86, 32-bit ARM): 64-bit x86
**OpenSlide version**: Openslide 3.4.1
**Slide format** (e.g. SVS, NDPI, MRXS): SVS

## Details

I am installing openslide for processing whole slide images. I downloaded openslide-3.4.1.tar.gz file from [https://openslide.org/download/](https://openslide.org/download/) and unzipped it. Then I followed the instructions given in readme.md:
 ./configure
 make
 make install

However, when I run make install command it says there is no rule to make target 'install' . I am unable to build openslide. How to solve this?

**Comment by bgilbert** [comment]
Please post a log of the commands you ran and the resulting output.

But also, if you're using Ubuntu, it'd be easier to install Ubuntu's binary package using the instructions on the download page.

**Comment by Abhinav-Telukunta** [comment]
@bgilbert I am running the code in Google Colab
```
!unzip /content/drive/MyDrive/openslide-3.4.1.zip
```
Archive:  /content/drive/MyDrive/openslide-3.4.1.zip
   creating: openslide-3.4.1/
  inflating: openslide-3.4.1/configure.ac  
  inflating: openslide-3.4.1/install-sh  
  inflating: openslide-3.4.1/README.txt  
  inflating: openslide-3.4.1/openslide.pc.in  
  inflating: openslide-3.4.1/config.guess  
  inflating: openslide-3.4.1/config.sub  
  inflating: openslide-3.4.1/CHANGELOG.txt  
  inflating: openslide-3.4.1/LICENSE.txt  
  inflating: openslide-3.4.1/CONTRIBUTING.txt  
  inflating: openslide-3.4.1/Makefile.am  
  inflating: openslide-3.4.1/missing  
  inflating: openslide-3.4.1/config.h.in  
  inflating: openslide-3.4.1/compile  
  inflating: openslide-3.4.1/ltmain.sh  
  inflating: openslide-3.4.1/lgpl-2.1.txt  
  inflating: openslide-3.4.1/depcomp  
  inflating: openslide-3.4.1/aclocal.m4  
  inflating: openslide-3.4.1/Makefile.in  
  inflating: openslide-3.4.1/configure  
   creating: openslide-3.4.1/m4/
  inflating: openslide-3.4.1/m4/ltoptions.m4  
  inflating: openslide-3.4.1/m4/lt~obsolete.m4  
  inflating: openslide-3.4.1/m4/ltversion.m4  
  inflating: openslide-3.4.1/m4/visibility.m4  
  inflating: openslide-3.4.1/m4/libtool.m4  
  inflating: openslide-3.4.1/m4/ltsugar.m4  
   creating: openslide-3.4.1/src/
  inflating: openslide-3.4.1/src/openslide-decode-xml.h  
  inflating: openslide-3.4.1/src/openslide-vendor-hamamatsu.c  
  inflating: openslide-3.4.1/src/openslide-tables.c  
  inflating: openslide-3.4.1/src/openslide-decode-tiff.c  
  inflating: openslide-3.4.1/src/openslide-decode-tiff.h  
  inflating: openslide-3.4.1/src/openslide-vendor-ventana.c  
  inflating: openslide-3.4.1/src/openslide-vendor-philips.c  
  inflating: openslide-3.4.1/src/openslide-decode-sqlite.h  
  inflating: openslide-3.4.1/src/openslide-hash.h  
  inflating: openslide-3.4.1/src/openslide-grid.c  
  inflating: openslide-3.4.1/src/openslide-cairo.h  
  inflating: openslide-3.4.1/src/openslide.c  
  inflating: openslide-3.4.1/src/openslide-vendor-trestle.c  
  inflating: openslide-3.4.1/src/openslide-private.h  
  inflating: openslide-3.4.1/src/openslide-decode-tifflike.c  
  inflating: openslide-3.4.1/src/openslide-decode-tifflike.h  
  inflating: openslide-3.4.1/src/openslide-decode-gdkpixbuf.c  
  inflating: openslide-3.4.1/src/openslide-decode-png.h  
  inflating: openslide-3.4.1/src/openslide.h  
  inflating: openslide-3.4.1/src/openslide-dll.rc  
  inflating: openslide-3.4.1/src/openslide-vendor-sakura.c  
  inflating: openslide-3.4.1/src/openslide-jdatasrc.c  
  inflating: openslide-3.4.1/src/openslide-vendor-generic-tiff.c  
  inflating: openslide-3.4.1/src/openslide-vendor-mirax.c  
  inflating: openslide-3.4.1/src/openslide-features.h  
  inflating: openslide-3.4.1/src/openslide-decode-gdkpixbuf.h  
  inflating: openslide-3.4.1/src/openslide-dll.rc.in  
  inflating: openslide-3.4.1/src/openslide-decode-jpeg.h  
  inflating: openslide-3.4.1/src/openslide-util.c  
  inflating: openslide-3.4.1/src/openslide-dll.manifest.in  
  inflating: openslide-3.4.1/src/openslide-error.h  
  inflating: openslide-3.4.1/src/openslide-decode-jp2k.c  
  inflating: openslide-3.4.1/src/openslide-decode-png.c  
  inflating: openslide-3.4.1/src/make-tables.c  
  inflating: openslide-3.4.1/src/openslide-decode-jpeg.c  
  inflating: openslide-3.4.1/src/openslide-decode-sqlite.c  
  inflating: openslide-3.4.1/src/openslide-hash.c  
  inflating: openslide-3.4.1/src/openslide-cache.c  
  inflating: openslide-3.4.1/src/openslide-vendor-aperio.c  
  inflating: openslide-3.4.1/src/openslide-decode-jp2k.h  
  inflating: openslide-3.4.1/src/openslide-vendor-leica.c  
  inflating: openslide-3.4.1/src/openslide-error.c  
  inflating: openslide-3.4.1/src/openslide-decode-xml.c  
   creating: openslide-3.4.1/test/
  inflating: openslide-3.4.1/test/parallel.c  
  inflating: openslide-3.4.1/test/test-common.h  
  inflating: openslide-3.4.1/test/try_open.c  
  inflating: openslide-3.4.1/test/test-common.c  
  inflating: openslide-3.4.1/test/mosaic.c  
  inflating: openslide-3.4.1/test/test.c  
  inflating: openslide-3.4.1/test/extended.c  
  inflating: openslide-3.4.1/test/profile.c  
  inflating: openslide-3.4.1/test/query.c  
  inflating: openslide-3.4.1/test/driver.in  
  inflating: openslide-3.4.1/test/symlink.c  
   creating: openslide-3.4.1/doc/
   creating: openslide-3.4.1/doc/html/
  inflating: openslide-3.4.1/doc/html/tab_a.png  
  inflating: openslide-3.4.1/doc/html/globals_func.html  
  inflating: openslide-3.4.1/doc/html/tabs.css  
  inflating: openslide-3.4.1/doc/html/dynsections.js  
  inflating: openslide-3.4.1/doc/html/openslide_8h.html  
  inflating: openslide-3.4.1/doc/html/globals_type.html  
  inflating: openslide-3.4.1/doc/html/bc_s.png  
  inflating: openslide-3.4.1/doc/html/folderopen.png  
  inflating: openslide-3.4.1/doc/html/index.html  
  inflating: openslide-3.4.1/doc/html/doxygen.png  
  inflating: openslide-3.4.1/doc/html/sync_off.png  
  inflating: openslide-3.4.1/doc/html/globals_defs.html  
  inflating: openslide-3.4.1/doc/html/nav_h.png  
  inflating: openslide-3.4.1/doc/html/openslide_8h_source.html  
  inflating: openslide-3.4.1/doc/html/arrowdown.png  
  inflating: openslide-3.4.1/doc/html/dir_68267d1309a1af8e8297ef4c3efbcdba.html  
  inflating: openslide-3.4.1/doc/html/globals.html  
  inflating: openslide-3.4.1/doc/html/pages.html  
  inflating: openslide-3.4.1/doc/html/nav_g.png  
  inflating: openslide-3.4.1/doc/html/closed.png  
  inflating: openslide-3.4.1/doc/html/tab_h.png  
  inflating: openslide-3.4.1/doc/html/open.png  
  inflating: openslide-3.4.1/doc/html/tab_b.png  
  inflating: openslide-3.4.1/doc/html/doxygen.css  
  inflating: openslide-3.4.1/doc/html/jquery.js  
  inflating: openslide-3.4.1/doc/html/splitbar.png  
  inflating: openslide-3.4.1/doc/html/tab_s.png  
  inflating: openslide-3.4.1/doc/html/bdwn.png  
  inflating: openslide-3.4.1/doc/html/files.html  
  inflating: openslide-3.4.1/doc/html/arrowright.png  
  inflating: openslide-3.4.1/doc/html/sync_on.png  
  inflating: openslide-3.4.1/doc/html/nav_f.png  
  inflating: openslide-3.4.1/doc/html/deprecated.html  
  inflating: openslide-3.4.1/doc/html/folderclosed.png  
  inflating: openslide-3.4.1/doc/html/doc.png  
  inflating: openslide-3.4.1/doc/Doxyfile  
   creating: openslide-3.4.1/tools/
  inflating: openslide-3.4.1/tools/openslide-quickhash1sum.c  
  inflating: openslide-3.4.1/tools/openslide-show-properties.1.in  
  inflating: openslide-3.4.1/tools/openslide-tools-common.c  
  inflating: openslide-3.4.1/tools/openslide-show-properties.c  
  inflating: openslide-3.4.1/tools/openslide-write-png.1.in  
  inflating: openslide-3.4.1/tools/openslide-write-png.c  
  inflating: openslide-3.4.1/tools/openslide-tools-common.h  
  inflating: openslide-3.4.1/tools/openslide-quickhash1sum.1.in 

```
!/content/openslide-3.4.1/configure
```
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for gcc option to accept ISO C99... none needed
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking for _LARGEFILE_SOURCE value needed for large files... no
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for uintptr_t... yes
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
/content/openslide-3.4.1/configure: line 7144: /usr/bin/file: No such file or directory
checking for mt... no
checking if : is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking for windres... no
checking version string... 3.4.1
checking for library containing floor... -lm
checking for library containing jpeg_CreateDecompress... -ljpeg
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for ZLIB... yes
checking for OPENJPEG2... yes
checking for LIBTIFF... yes
checking for GLIB2... yes
checking for CAIRO... no
configure: error: Package requirements (cairo >= 1.2) were not met:

No package 'cairo' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables CAIRO_CFLAGS
and CAIRO_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

```
!chmod +x /content/openslide-3.4.1/Makefile.in
```

```
!make install
```
**make: *** No rule to make target 'install'.  Stop.**

**Comment by jaharkes** [comment]
Looks like you are missing the cairo library. Configure never completed and didn't create the makefiles.
Once configure finds all the required libraries it will generate the proper Makefiles for you by combining the discovered system configuration (library installation paths and such) and the Makefile.in templates, but without those libraries it can't do anything for you.
