### ISSUE TITLE
how to crop .mrxs files 

### ISSUE THREAD

**Issue by niloofarmaani1** [openslide/openslide#327]
I am new to this library,
I have a .mrxs file that I want to crop and the crop area should again be a high-resolution image because we need this for annotation.
I wanted to know is this possible using openslide?
crop an area without losing resolution?

Thanks

**Comment by bgilbert** [comment]
Just pass `level` 0 to `openslide_read_region()`.  That'll always return the highest resolution image level.

Please send support questions to the openslide-users mailing list.  This issue tracker is for bug reports and enhancement requests.
