### ISSUE TITLE
Detect pyramidal generic tiffs that don't have SUBFILETYPE set to FILETYPE_REDUCEDIMAGE

### ISSUE THREAD

**Issue by j-hudecek** [openslide/openslide#328]
## Context

**Issue type** (bug report or feature request): feature request
**Operating system** (e.g. Fedora 24, Mac OS 10.11, Windows 10): all
**Platform** (e.g. 64-bit x86, 32-bit ARM): all
**OpenSlide version**: 3.4.1
**Slide format** (e.g. SVS, NDPI, MRXS): generic-tiff

## Details
I've received a few images (not sure how were they created) that look like this 

	$tiffinfo pyramid.tif
	TIFF Directory at offset 0x2e4ee6f2 (776922866)
	  Subfile Type: (0 = 0x0)
	  Image Width: 34816 Image Length: 60928
	  Tile Width: 512 Tile Length: 512
	  Resolution: 1, 1 pixels/cm
	  Bits/Sample: 8
	  Sample Format: unsigned integer
	  Compression Scheme: LZW
	  Photometric Interpretation: RGB color
	  Orientation: row 0 top, col 0 lhs
	  Samples/Pixel: 3
	  SMin Sample Value: 0
	  SMax Sample Value: 255
	  Planar Configuration: single image plane
	TIFF Directory at offset 0x3cc8e6da (1019799258)
	  Subfile Type: (0 = 0x0)
	  Image Width: 17408 Image Length: 30464
	  Tile Width: 512 Tile Length: 512
	  Resolution: 0.5, 0.5 pixels/cm
	  Bits/Sample: 8
	  Sample Format: unsigned integer
	  Compression Scheme: LZW
	  Photometric Interpretation: RGB color
	  Orientation: row 0 top, col 0 lhs
	  Samples/Pixel: 3
	  Planar Configuration: single image plane
	TIFF Directory at offset 0x40ca2442 (1086989378)
	  Subfile Type: (0 = 0x0)
	  Image Width: 8704 Image Length: 15232
	  Tile Width: 512 Tile Length: 512
	  Resolution: 0.25, 0.25 pixels/cm
	  Bits/Sample: 8
	  Sample Format: unsigned integer
	  Compression Scheme: LZW
	  Photometric Interpretation: RGB color
	  Orientation: row 0 top, col 0 lhs
	  Samples/Pixel: 3
	  Planar Configuration: single image plane
      ....

i.e. they clearly contain multiple pyramidal levels but don't have the SUBFILETYPE (254) set to FILETYPE_REDUCEDIMAGE (1)

OpenSlide doesn't recognize the levels which leads to terrible performance when reading reduced resolution tiles:

	$ OPENSLIDE_DEBUG=detection openslide-show-properties pyramid.tif
	Openslide-Message: 22:57:08.839: mirax: Is a TIFF file
	Openslide-Message: 22:57:08.839: hamamatsu-vms-vmu: Is a TIFF file
	Openslide-Message: 22:57:08.839: hamamatsu-ndpi: No TIFF tag 65420
	Openslide-Message: 22:57:08.839: sakura: Is a TIFF file
	Openslide-Message: 22:57:08.839: trestle: No such value: directory 0, tag 305
	Openslide-Message: 22:57:08.839: aperio: No such value: directory 0, tag 270
	Openslide-Message: 22:57:08.839: leica: No such value: directory 0, tag 270
	Openslide-Message: 22:57:08.839: philips: No such value: directory 0, tag 305
	Openslide-Message: 22:57:08.839: ventana: No such value: directory 0, tag 700
	openslide.level-count: '1'
	openslide.level[0].downsample: '1'
	openslide.level[0].height: '121856'
	openslide.level[0].tile-height: '512'
	openslide.level[0].tile-width: '512'
	openslide.level[0].width: '61440'
	openslide.vendor: 'generic-tiff'
	tiff.ResolutionUnit: 'centimeter'
	tiff.XResolution: '1'
	tiff.YResolution: '1'

(the detection code is at https://github.com/openslide/openslide/blob/c3391de109f736e8164bec27176e42bacae462a5/src/openslide-vendor-generic-tiff.c#L204). 

If I run 

	for i in $(seq 1 `tiffinfo pyramid.tif | grep TIFF | wc -l`)
	do 
		tiffset -d $i -s 254 1 pyramid.tif
	done

to "fix" the SUBFILETYPE to 1 for all directories except the first (yes there is an off by one error for the last one) it detects the levels correctly.

It would be neat if that wasn't necessary and openslide read the directories and checked if it's a pyramid. If not perhaps this issue will help someone else at least

**Comment by bgilbert** [comment]
Thanks for the report.  OpenSlide intentionally doesn't detect generic TIFFs as pyramidal unless the downsampled directories have `FILETYPE_REDUCEDIMAGE` set.  If the file claims not to be pyramidal, we choose to believe it.  :slightly_smiling_face:

The generic tiled TIFF driver is really only meant for well-formed TIFF files.  TIFFs that are more idiosyncratic outputs of particular programs should probably have their own vendor drivers instead.

**Comment by vrishk** [comment]
When I try to use `tiffset` to convert the tiff, I get a change in the color of the tiff. The background which is usually white (light gray) turns reddish pink and there are other changes throughout the image. Do you know why this could be occurring?

**Comment by bgilbert** [comment]
@vrishk No, that's odd.  If your viewer respects ICC profiles, you might check that the profile is being preserved by the conversion.

Per https://github.com/openslide/openslide/issues/328#issuecomment-831551605, I don't think there are any changes to be made in the `generic-tiff` driver, so I'll close.  If the file format is being produced by a particular scanner, we could consider adding a new vendor driver to support it.
