### ISSUE TITLE
Aperio AppMag inconsistent representation.

### ISSUE THREAD

**Issue by lromor** [openslide/openslide#332]
## Context

**Issue type** (bug report or feature request): bug
**Operating system** (e.g. Fedora 24, Mac OS 10.11, Windows 10): all 
**Platform** (e.g. 64-bit x86, 32-bit ARM): x86 64-bit
**OpenSlide version**: 3.4.1
**Slide format** (e.g. SVS, NDPI, MRXS): SVS

## Details

We noticed some edge cases that do not allow the current openslide aperio implementation to parse correctly the AppMag of the WSI.

An example image is provided at this link: 
https://portal.gdc.cancer.gov/files/1fd8ba85-547b-435f-830e-a436746990fd 

Using tiffinfo you can see that:
95744x86336 (256x256) J2K/KDU Q=70;Leica SCN400;Leica SCN ver.1.5.1.10804 2012/05/10 13:29:07;1.5.1.10864|Filename = ImageCollection_0000000935|Date = 2014-07-23T16:33:58.37Z|AppMag = 40.000000|MPP = 0.250000|OriginalWidth = 86336|OriginalHeight = 95744
As you can see, the AppMag metadata is represented as a float value instead as of an int (|AppMag = 40|) . This leads to an unparsed AppMag. We propose to change "_openslide_duplicate_int_prop" into "_openslide_duplicate_double_prop" or allow the int version to parse and then cast float values in the following line of code:

https://github.com/openslide/openslide/blob/c3391de109f736e8164bec27176e42bacae462a5/src/openslide-vendor-aperio.c#L327

What are your thoughts on this?

Best,

Leo

**Comment by bgilbert** [comment]
Thanks for the report!
