### ISSUE TITLE
Read compressed tile bytes

### ISSUE THREAD

**Issue by JasonRuan5** [openslide/openslide#339]
## Context

**Issue type** (feature request): 
**Operating system** (Windows 10): 
**Platform** (64-bit): 
**OpenSlide version**:  (latest)
**Slide format** (Tif, SVS, NDPI): 

## Details

We would like to read compressed tile buffer and have noticed an _openslide_tiff_read_tile_data method in openslide-decode-tiff.cpp, which seems to do exactly what we need.  How can we call the method in Visual Studio 2019?  We have downloaded OpenSlide for Windows, but there is no corresponding method.  What can we do?

**Comment by bgilbert** [comment]
Could you elaborate on your use case?  OpenSlide is generally designed to provide uncompressed pixel data to the application, performing decompression and tile decoding on its behalf.

**Comment by JasonRuan5** [comment]
I was hoping to use OpenSlide to read compressed tile pixel data.  Is this possible?  I did find a way to do so using libtiff.

**Comment by bgilbert** [comment]
Nope, that functionality is outside the scope of OpenSlide.  Doing it through libtiff is the way to go.
