### ISSUE TITLE
Bad use of 'level' parameter in openslide_read_region() function

### ISSUE THREAD

**Issue by Franm99** [openslide/openslide#341]
## Context

As far as I have understood about how the `level` parameter inside the `openslide_read_region()` works, if I use a value different from 0, the read process will be executed in a subsampled version of the whole-slide image pointed by `openslidePointer` variable. For instance, if my whole-slide image allows 6 levels, if I decide using `level=5`, my subsampled image will have a subsampling factor of 2^5 = 32.

## Problem

I found out that using a level different from 0 (default value), an error occurs: 

> `Error: Invalid text character. Check for unsuported symbol, invisible character, or pasting of non-ASCII characters.`

So I opened the source code of the function, finding the reason rising the error in lines 42-44:

```
for k=1:2:length(varargin)
    eval([varargin{k},'=varargin{',int2str(k+1),'};']);
end
```

I can't understand why these lines are used, because previously level is initialized to 0 and then never changed, even if the user specifies a different value when calling the function. In addition, this loop rises the error, as the evaluation has not sense. for instance, if `level=2` is used, the evaluation is made as follows:

> `2=varargin{2};`

Rising the error aforementioned.

## Solution

I think the issue can be solved just substituting these lines with the following:

> `level = varargin{1}`

As no more input arguments are expected to be used, and the goal of this `varargin` list is to modify the `level` parameter.

Please, let me know if I'm wrong with my understanding of this function, and if the solution I propose is correct or whether a different use of the `varargin` input parameter is expected.

Best regards.

Fran Moreno.

**Comment by jaharkes** [comment]
There is no reference to 'varargin' anywhere in the Openslide code base, which is implemented in C.

Very detailed, but ultimately useless report, looks like a coding error in whatever program you were looking at.

It seems like they are trying to implement a way to 'pop' a processed argument off of a list of arguments, similar to `shift` in a Bourne shell script. I'm not entirely sure why it needs to pass generated code to an eval statement to do that, it is either very badly written code, or a horrible language to write code for.

**Comment by jaharkes** [comment]
Looks like the problem is with the matlab bindings, thanks @bgilbert for pointing me in the right direction and it may just be using an odd calling convention.
Instead of just adding the value of the level. as an optional argument, it expects two arguments, 'level', and then the level you want to set. So instead of passing level=2, which probably evaluates to just the number 2, use ..., "level", 2) which then makes the string eval(["level = 2"]); still horrible code and yes, just doing the assignment you propose is a lot cleaner but it changes the API of the binding.

**Comment by bgilbert** [comment]
> For instance, if my whole-slide image allows 6 levels, if I decide using level=5, my subsampled image will have a subsampling factor of 2^5 = 32.

Actually, the subsampling factor on a downsampled level depends on the levels stored in the slide file.  You can use `openslide_get_level_downsample()` to see the downsample of a level.

**Comment by bgilbert** [comment]
Also, it appears that openslide-matlab expects `openslide_read_region` arguments in a different order than OpenSlide:

```matlab
openslide_read_region(ptr, x, y, w, h, 'level', lvl)
```
