### ISSUE TITLE
Add support for Apple Silicon

### ISSUE THREAD

**Issue by juanigp** [openslide/openslide#345]
## Context

**Issue type** (bug report or feature request):  Feature request
**Operating system** (e.g. Fedora 24, Mac OS 10.11, Windows 10): macOS Big Sur 
**Platform** (e.g. 64-bit x86, 32-bit ARM): M1 (ARM 64)
**OpenSlide version**: -
**Slide format** (e.g. SVS, NDPI, MRXS): -

## Details

Add support for Apple Silicon processors. Currently I had to install homebrew and openslide with rosetta, but a native version of openslide should be available.

**Comment by bgilbert** [comment]
OpenSlide should run fine on ARM processors.  The OpenSlide project only releases source code, not binaries (except on Windows); it's up to downstream packagers to provide compiled binaries.

If OpenSlide isn't available for ARM in Homebrew, you could raise the issue with the Homebrew maintainers.  Alternatively, OpenSlide is also packaged in MacPorts, and I believe ARM packages are available there.
