### ISSUE TITLE
NDPI slide has three similar tissue sections - only need to partition one

### ISSUE THREAD

**Issue by AuritaP** [openslide/openslide#350]
## Context

**Issue type** (feature request): No idea how to do it
**Operating system** ( Windows 10): 
**Platform** (64-bit x86)
**OpenSlide version**: win64-20171122
**Slide format** ( NDPI): 

## Details
I have lots of slides scanned at 40X and each one of them have either 3 or 2 sequential sections of my tissues, just to be sure we got a good section. I really only need to partition one of the sections, is there a way that I can tell the program to do that rather than using the whole slide? I am already using the -b option to get rid of background and even using a patch size of 2000, I am generating lots of tiles for just that one slide and of course they are more or less repeated.

**Comment by bgilbert** [comment]
You should be able to use the `openslide.region[N]` properties to get the bounding box of each section.
