### ISSUE TITLE
` DeepZoomGenerator.get_tile` documentation has wrong address tuple order

### ISSUE THREAD

**Issue by vahvero** [openslide/openslide#352]
## Context

**Issue type** (bug report or feature request): Documentation error
**Operating system** (e.g. Fedora 24, Mac OS 10.11, Windows 10): Non-applicable
**Platform** (e.g. 64-bit x86, 32-bit ARM): Non-applicable
**OpenSlide version**: 3.4.1
Slide format** (e.g. SVS, NDPI, MRXS): Non-applicable

## Details

In the [documentation](https://openslide.org/api/python/#openslide.deepzoom.DeepZoomGenerator.get_tile), `get_tile` documentation reads as follows

> get_tile(level, address)
> Return an RGB [Image] https://pillow.readthedocs.io/en/latest/reference/Image.html#PIL.Image.Image) for a tile.
> Parameters
> level ([int](https://docs.python.org/3/library/functions.html#int)) – the Deep Zoom level
> address ([tuple](https://docs.python.org/3/library/stdtypes.html#tuple)) – the address of the tile within the level as a **(column, row)** tuple

However, when using this with code sample

```python
def dzi_generator_speed():
    slide = openslide.OpenSlide(SVS_FILE)
    slide_image = DeepZoomGenerator(slide, tile_size=TILE_SIZE, overlap=0)
    level = slide_image.level_count - 1
    rows, cols = slide_image.level_tiles[level]
    for row, col in product(range(rows), range(cols)):
        tile = slide_image.get_tile(level, (col, row))
        yield np.asarray(tile)
```

Causes error `ValueError: Invalid address`. Changing the code to

```python
def dzi_generator_speed():
    slide = openslide.OpenSlide(SVS_FILE)
    slide_image = DeepZoomGenerator(slide, tile_size=TILE_SIZE, overlap=0)
    level = slide_image.level_count - 1
    rows, cols = slide_image.level_tiles[level]
    for row, col in product(range(rows), range(cols)):
        tile = slide_image.get_tile(level, (row, col)) # <-- changed to row, col
        yield np.asarray(tile)
```
Runs with no errors. The documentation seems to have wrong tuple order.

**Comment by bgilbert** [comment]
`level_tiles` contains tuples of `(cols, rows)`, so your failing code is reading the pairs backwards and then swapping them for the call to `get_tile`.  Keeping everything in `(cols,  rows)` order should fix your issue.

**Comment by vahvero** [comment]
[Level tiles](https://openslide.org/api/python/#openslide.deepzoom.DeepZoomGenerator.level_tiles) reads as list of `(tiles_x, tiles_y)` which would suggest that they have form of `row_tile, col_tile`. One of the facts seems to be, if not incorrect, then misleading.

**Comment by bgilbert** [comment]
As is common in a lot of imaging, the `x` coordinate specifies a column and the `y` coordinate specifies a row.

**Comment by vahvero** [comment]
It seems that I have personally learnt to use a different ordering where `x` is always the row and `y` is always the column.

Nevertheless, I would still suggest resigning from using these single character variables. They can always be better described by "width" and "height" or with "row" and "column" when referring to these coordinates in documentation. For example, Torch, OpenCV and NumPy all have different order of image dimensions which makes the current approach slightly ambiguous.

I understand that if the characters `x` and `y` have been chosen by their cultural significance, for the vast majority of the users the documentation is clear. I would still like to suggest a more spelled out approach as mentioned in the previous paragraph.
