### ISSUE TITLE
Convert text files to Markdown

### ISSUE THREAD

**Issue by logankilpatrick** [openslide/openslide#354]
I am going to switch some of the txt files to markdown so that we get the nice rendering on GitHub. I will separately open a PR to add an initial code of conduct, we can discuss the details in both PR's but wanted to open this as a tracker for myself.

**Comment by bgilbert** [comment]
Sounds great, thanks!

**Comment by bgilbert** [comment]
Let's use the existing #306 to track the CoC part.

**Comment by bgilbert** [comment]
I ended up implementing this across all of our repos in the course of a larger docs migration/cleanup.  In the main OpenSlide repo it was done in https://github.com/openslide/openslide/pull/357.

Thanks for raising this!
