### ISSUE TITLE
Stop printing out stuff when probing TIFF files

### ISSUE THREAD

**Issue by agoode** [openslide/openslide#36]
_Imported from Trac. This issue originally by *_agoode*\* at 2010-05-04T17:08:54Z.*

libtiff prints out lots of warnings without our knowledge. If libtiff provided a library- and reentrant-safe way of turning this off, we should do it.

**Comment by bgilbert** [comment]
libtiff 4.5.0 adds [private error/warning handlers](http://www.simplesystems.org/libtiff/functions/TIFFOpenOptions.html).  Once we can assume a new enough libtiff, that should allow us to drop [our own magic checks](https://github.com/openslide/openslide/blob/3502f0dad8df459c00b332a1fc319cea7447a9dc/src/openslide-decode-tiff.c#L569).

**Comment by bgilbert** [comment]
Fix in https://github.com/openslide/openslide/pull/569.  It turns out that we can drop the magic checks immediately, since we only open files through libtiff if tifflike can read them.
