### ISSUE TITLE
Allow cache customization

### ISSUE THREAD

**Issue by agoode** [openslide/openslide#38]
_Imported from Trac. This issue originally by *_agoode*\* at 2010-05-04T17:12:56Z.*

Right now, we have a simple per-slide cache that is not shared. There should be a way to allow a user to do caching themselves, or not at all if it is a one-pass run. Perhaps the user can provide a cache themselves, run uncached and cache everything themselves.

**Comment by GeertLitjens** [comment]
This is a very old issue, but I added a simple set_cache_size function to openslide to allow user to disable the cache. This is useful in some of my applications where I keep an opened file handle to the whole-slide image for 100s of images. Allowing them all to have their own cache creates a lot of memory use when reading pixel data. Would a pull request be of any interest?

**Comment by bgilbert** [comment]
@GeertLitjens Thanks for the feedback!  If your change is non-trivial, a PR would be interesting for reference purposes (not for merging) -- or feel free to just link to a commit/diff.  Ultimately we'd probably want to implement a slightly more general API along the lines of the description above; that would allow the application to maintain e.g. one giant cache shared by all slide handles.  Would that functionality be useful for your application?

**Comment by AlexanderVanEck** [comment]
@bgilbert this ticket could be closed as this mechanism already exists. 👍  see https://github.com/openslide/openslide/pull/331

https://github.com/openslide/openslide/blob/c3391de109f736e8164bec27176e42bacae462a5/src/openslide-cache.c#L180

& 

https://github.com/openslide/openslide/blob/c3391de109f736e8164bec27176e42bacae462a5/src/openslide-cache.c#L173

**Comment by bgilbert** [comment]
@AlexanderVanEck Those functions are internal to OpenSlide, and aren't part of the external API.

**Comment by bgilbert** [comment]
Candidate implementation in #335.
