### ISSUE TITLE
How can I rotate the area of interest of read_region function?

### ISSUE THREAD

**Issue by lkhangkv1995** [openslide/openslide#399]
## Context

**Issue type:** feature request

## Details
Hello

In my understanding, the OpenSlide.read_region(location=location, size=size, level=level) gives us patches with size=size and these patches have same x and y direction to the OpenSlide object. 
Is it possible for us to rotate the patch? I mean we get the patch with x and y coordinates rotated compared to the x and y coordinates of the OpenSlide references.

I would appreciate it if you can help me with this.
Thank you very much!

![example](https://user-images.githubusercontent.com/98082429/195968321-8fec8392-be93-4bf3-bbcd-e3ad118fa42e.png)

**Comment by bgilbert** [comment]
That's something you'll need to do in your own software after reading the relevant region from the slide file.  OpenSlide is only responsible for returning data from the slide; it doesn't handle any further image processing.
