### ISSUE TITLE
Unresolved issue with extraction of a particular region of NDPI slide image

### ISSUE THREAD

**Issue by AuritaP** [openslide/openslide#400]
## Context

**Issue type** (bug report or feature request): Still no idea how to do it
**Operating system** (e.g. Fedora 24, Mac OS 10.11, Windows 10): Windows 10
**Platform** (e.g. 64-bit x86, 32-bit ARM): 64bit-bit x86 Running program in Linux
**OpenSlide version**: 3.4.0
**Slide format** (e.g. SVS, NDPI, MRXS): NDPI

## Details
I have NDPI slides scanned at 40x, each slide has three (some 2) sections. I only need to generate tiles using openslide from one of the sections so I can go into Quick annotator and develop a model to identify structures that I want. An example of the slide is attached
![Sample NDPI](https://user-images.githubusercontent.com/26971096/198322668-216b7fa8-036a-48e3-b04e-1b6050ebab7e.jpg)

Usually the best section is the middle one, so I am trying to tell openslide to only make patches of that section only, but at this point I settle for any one. It was suggested to me to use the openslide.region[N] for this purpose. I have read a lot and tried a lot of things, and even though I have learned a lot, clearly I still don't know how to do it. To compound things, I need to extract the patches at 20x or even 10x, to give the model more information that it can get with the 40x.

Using the -l command in the script below, I know I can get 20x with -l1 and 10x with -l2. But still of the whole slide. I am pasting below the script that QuickAnotator uses to generate patches with open slide. I have added the line indicated in BOLD to tell the program to read just the region that I indicate when I ran the program. It seems that is processing that line since when I ran the program it says that it is doing it, but since I have changed the value that I use for that argument in many different ways and I get the same result is really not working, even if I don't include the argument still get the same results.

I have tried to understand how that openslide-region should be used, but clearly, I am not getting it.

Besides the script, I have included one of the runs that I have done.

Script

```python
# ---
# jupyter:
#   jupytext:
#     formats: ipynb,py:light
#     text_representation:
#       extension: .py
#       format_name: light
#       format_version: '1.5'
#       jupytext_version: 1.4.1
#   kernelspec:
#     display_name: Python 3
#     language: python
#     name: python3
# ---

import os
import cv2
import glob
import argparse
import traceback
import sys
import json
import numpy as np
import sklearn.feature_extraction.image
from pathlib import Path
from tqdm.autonotebook import tqdm

import openslide


# +
parser = argparse.ArgumentParser(description='Convert image and mask into non-overlapping patches')
**parser.add_argument('-openslide_read_region','--openslide_read_region)**
parser.add_argument('-p', '--patchsize', help="Patchsize, default 1000", default=1000, type=int)
parser.add_argument('-l', '--openslidelevel', help="openslide level to use", default=0, type=int)
parser.add_argument('-o', '--outdir', help="Target output directory", default="./output", type=str)
parser.add_argument('-b', '--bgremoved',  action="store_true", help="Don't save patches which are considered background, useful for TMAs")
parser.add_argument('input_pattern', help="Input filename pattern (try: *.png), or txt  file containing list of files", nargs="*")

#args = parser.parse_args(["-l1","-b","-p2000",r"D:\research\chuv_melanoma\Patient 1\M160902-HE.svs"])
args = parser.parse_args()
print(f"args: {args}")
print(f"USER: Starting make patches for {args.outdir}", flush=True)


# +
patch_size = args.patchsize
outdir = args.outdir + os.sep if len(args.outdir) > 0 else ""  # if the user supplied a different basepath, make sure it ends with an os.sep
level = args.openslidelevel

if not os.path.isdir(f"{outdir}"):
    os.mkdir(f"{outdir}")



# +
fnames = []

if len(args.input_pattern) > 1:  # bash has sent us a list of files
    fnames = args.input_pattern
elif args.input_pattern[0].endswith("txt"):  # user sent us an input file
    with open(args.input_pattern[0], 'r') as f:
        for line in f:
            fnames.append(line.strip())
else:  # user sent us a wildcard, need to use glob to find files
    fnames = glob.glob(args.input_pattern[0])


# +
print(f"Identified {len(fnames)} image(s)")

for ii,fname in tqdm(enumerate(fnames),leave=False):
    fnamebase=Path(os.path.basename(fname)).stem
    
    print(f"{fname}")
    fnamebase = os.path.splitext(os.path.basename(fname))[0]

    osh  = openslide.OpenSlide(fname)
    nrow,ncol = osh.level_dimensions[0]

    for y in tqdm(range(0,osh.level_dimensions[0][1],round(patch_size * osh.level_downsamples[level])), desc="outer" , leave=False):
        for x in tqdm(range(0,osh.level_dimensions[0][0],round(patch_size * osh.level_downsamples[level])), desc=f"innter {y}", leave=False):
    
            
            patch  = np.asarray(osh.read_region((x, y), level, (patch_size,patch_size)))[:,:,0:3] #trim alpha

            if(args.bgremoved):
                gpatchmean = cv2.cvtColor(patch, cv2.COLOR_BGR2GRAY).mean()
                if(gpatchmean>200 or gpatchmean<50):
                    continue

        
            patch=cv2.cvtColor(patch,cv2.COLOR_RGB2BGR)
            cv2.imwrite(f"{outdir}{fnamebase}_{level}_{y}_{x}.png", patch)

    osh.close()


print(f"Done making patches!")
```

---

How I ran one of the many trials

```console
(IMGcrunch) [axp8@exon cli]$ python extract_tiles_from_wsi_openslide_5thTEST.py ../../../PAS\ D-54584\ SR5\ -\ 2022-03-07\ 17.59.17.ndpi -openslide_read_region 76000,6000,0,1000,1000 -b -l 0 -p 1000 -o /mnt/rds/genetics01/DrummLab/axp8/installs/QuickAnnotator/cli/regtest15th
args: Namespace(bgremoved=True, input_pattern=['../../../PAS D-54584 SR5 - 2022-03-07 17.59.17.ndpi'], openslide_read_region='76000,6000,0,1000,1000', openslidelevel=0, outdir='/mnt/rds/genetics01/DrummLab/axp8/installs/QuickAnnotator/cli/regtest15th', patchsize=1000)
USER: Starting make patches for /mnt/rds/genetics01/DrummLab/axp8/installs/QuickAnnotator/cli/regtest15th
Identified 1 image(s)
0it [00:00, ?it/s]../../../PAS D-54584 SR5 - 2022-03-07 17.59.17.ndpi
Done making patches!
```

These samples are done working at level 0, highest magnification, I figure if I can make it work there, then I can tackle the -l 1 or 2 magnifications

Any help to a non-programmer that is trying her best will be greatly appreciated

**Comment by bgilbert** [comment]
OpenSlide only provides the `openslide.region[N]` properties for slide formats that contain enough information to know where the individual regions are located.  As far as I know, Hamamatsu NDPI slides do not contain this information; they just have pixels.  Therefore, OpenSlide can't help you here.  However, you could probably find the regions yourself by reading the entire highest level (i.e. lowest resolution) and doing some image processing to locate the non-empty portions of the image.
