### ISSUE TITLE
[FEATURE REQUEST] Package as conan package

### ISSUE THREAD

**Issue by cincospenguinos** [openslide/openslide#401]
## Context

I work at [COMPANY NAME REDACTED], and we have a fork of openslide with a couple of extra features we need for our application. We have switched over to using [conan](https://conan.io/) as our internal package manager, and I would love to keep our internal fork of openslide up to date. Doing that the way we've put it together is a pain in the butt, and I'm not familiar with autotools enough to do it on my own very well.

My team and I don't have a _ton_ of bandwidth, but depending on general interest with y'all on setting up a conan package/configuring this package to be available in conan center, I'd be willing to help out and contribute wherever I can. It would help ~our business~ my team out immensely, and having openslide in conan may align with your team's wishes to make newer releases more readily available.

Regardless, this is your project, and I and my team will respect whatever y'all decide. I'd be more than happy to open a merge request demonstrating how we put together this project in conan with autotools as an example.

**Feature Request**
**Debian Bullseye**
**64-bit AMD**
**3.4.1**
**SVS/Generic TIFF**

**Comment by bgilbert** [comment]
Thanks for reaching out!  In general, we're happy for folks to add OpenSlide to package managers, and you don't need to ask permission first.  :slightly_smiling_face:  I'd be happy to help answer questions and/or glance at the proposed packaging, but would generally leave maintenance of the package to the community.

Note that in the upcoming months we'd like to switch to Meson (#316), which should make Windows builds easier, and which will also require packaging changes.  You may want to wait until then before building any new packaging.

**Comment by bgilbert** [comment]
Git `main` has now been switched to Meson, but Meson support isn't in a stable OpenSlide release yet.

**Comment by bgilbert** [comment]
The newly-released [OpenSlide 4.0.0](https://github.com/openslide/openslide/releases/tag/v4.0.0) builds with Meson.  If you're still interested in packaging it, let me know if there's anything I can do to help!

**Comment by bgilbert** [comment]
Since there currently aren't any plans to maintain Conan packages as part of the upstream OpenSlide project, I'll close this issue.  Still happy for the community to work on this!

**Comment by bgilbert** [comment]
A community member has submitted a PR in https://github.com/conan-io/conan-center-index/pull/21138.

**Comment by bgilbert** [comment]
Oh, and it looks like there's also https://github.com/conan-io/conan-center-index/pull/19592 for OpenSlide 3.4.1.
