### ISSUE TITLE
TIFFFillTile: 0: Invalid tile byte count, tile 1545.

### ISSUE THREAD

**Issue by 464hee** [openslide/openslide#406]
Why does openslip-python ==1.2.0 and openslide==3.4.1 still have this error?? :

TIFFFillTile: 0: Invalid tile byte count, tile 1545.

## Context

**Issue type** (bug report or feature request): 
TIFFFillTile: 0: Invalid tile byte count, tile 1545.

**Operating system** (e.g. Fedora 24, Mac OS 10.11, Windows 10): 
unbutu20.04
**Platform** (e.g. 64-bit x86, 32-bit ARM): 
x86
**OpenSlide Python version** (`openslide.__version__`): 
openslip-python ==1.2.0
**OpenSlide version** (`openslide.__library_version__`): 
[1102.zip](https://github.com/openslide/openslide-python/files/9989075/1102.zip)
openslide==3.4.1
**Slide format** (e.g. SVS, NDPI, MRXS): 
tif

**Comment by bgilbert** [comment]
OpenSlide 3.4.1 worked around this issue for Aperio slides (7e033bbb36bb50474a1921b976f99f69d87414a2), but didn't do that for other vendors because I don't think a valid TIFF file will have zero-length tiles.  Where did you get the affected TIFF file?

**Comment by 464hee** [comment]
> OpenSlide 3.4.1 worked around this issue for Aperio slides ([7e033bb](https://github.com/openslide/openslide/commit/7e033bbb36bb50474a1921b976f99f69d87414a2)), but didn't do that for other vendors because I don't think a valid TIFF file will have zero-length tiles. Where did you get the affected TIFF file?
I used openslide-3.4.1，This tif file can be opened and read using ASAP
[ASAP_read_tif.zip](https://github.com/openslide/openslide/files/9994000/ASAP_read_tif.zip)
This is code read using ASAP，But with the above error, I don't think the tif file is invalid because it is readable using ASAP and the correct results are returned

**Comment by 464hee** [comment]
I would like to know why ASAP can get the correct result, but opensilde returns an error. Openslide is a good tool library,I prefer to use openslide for development work, so I hope to get your help

**Comment by bgilbert** [comment]
Again, what software was used to create the TIFF file?  OpenSlide sometimes adds workarounds for file format bugs produced by scanner software, but does not try to support every possible TIFF variation produced by any source.

**Comment by 464hee** [comment]
I use the tif diagram created by ASAP,Because ASAP is very convenient for image annotation

> Again, what software was used to create the TIFF file? OpenSlide sometimes adds workarounds for file format bugs produced by scanner software, but does not try to support every possible TIFF variation produced by any source.

I use the tif diagram created by ASAP,Because ASAP is very convenient for image annotation

**Comment by bgilbert** [comment]
Okay, thanks for the information.  OpenSlide is primarily designed to decode slide files produced by whole-slide image scanners, and ASAP does not appear to capture data directly from scanner hardware.  Therefore, I'll close this.  You may wish to consider discussing this error with the maintainers of ASAP.
