### ISSUE TITLE
Windows Binaries  Request

### ISSUE THREAD

**Issue by dong-ma-zi** [openslide/openslide#411]
## Context

**Issue type** (bug report or feature request): feature request
**Operating system** (e.g. Fedora 24, Mac OS 10.11, Windows 10): Windows 10
**Platform** (e.g. 64-bit x86, 32-bit ARM): 64-bit x86
**OpenSlide version**: 2022-11-11
**Slide format** (e.g. SVS, NDPI, MRXS): dmetrix

## Details
Thank you for your excellent work. I'm in a collaborative project right now and I need to process WSI with .dmetrix format, using openslide. I noticed that you added .dmetrix format in pull requests#270, and built successfully on ubuntu1604. 
However, I need to deploy our project on Windows now, but I noticed that the latest release of Windows can not support the .dmetrix format, and I failed to build #270  on windwos. 
So, could you please provied me with the Windows Binaries with the support of dmetrix? I will be very appreciate !!

**Comment by bgilbert** [comment]
#270 was submitted by a member of the community and hasn't yet been merged into OpenSlide, so there are no official binaries.  However, you might be able to build for Windows yourself with the [override support](https://github.com/openslide/openslide-winbuild#substitute-sources) in openslide-winbuild.  If you clone the openslide-winbuild repository, you can create an `override/openslide` directory with a checkout of that PR, then build.  Note that you'll need to run `autoreconf -i` in the OpenSlide checkout before building, and you'll need to copy in `src/openslide-tables.c` from another build.
