### ISSUE TITLE
with black stripes，why?

### ISSUE THREAD

**Issue by zengnanhua** [openslide/openslide#418]
![image](https://user-images.githubusercontent.com/22017107/210721517-40fda4e0-06fb-4a81-bfa3-416838b8befd.png)

**Comment by bgilbert** [comment]
You haven't provided _any_ information to diagnose the issue.  Please fill out the original issue template:

**Operating system** (e.g. Fedora 24, Mac OS 10.11, Windows 10): 
**Platform** (e.g. 64-bit x86, 32-bit ARM): 
**OpenSlide version**: 
**Slide format** (e.g. SVS, NDPI, MRXS): 

Also explain what you're doing to get this image.

I'll close.  Feel free to reopen once you've provided information.
