### ISSUE TITLE
Image has many blank tiles in it

### ISSUE THREAD

**Issue by YubinXie** [openslide/openslide#426]
### Operating system

Linux

### Platform

64bit-python

### OpenSlide version

1.2.0

### Slide format

mrxs

### Issue details

The image shows in the data has many blank tiles. I checked several files and they have the same issues. I wonder what could possibly lead to this? Thanks!

<img width="428" alt="image" src="https://user-images.githubusercontent.com/16257776/212741140-8297038b-5372-4113-96c6-c74d6902b059.png">

**Comment by bgilbert** [comment]
This is likely due to https://github.com/openslide/openslide/issues/278.  What Linux distro version are you using?

**Comment by YubinXie** [comment]
> This is likely due to #278. What Linux distro version are you using?

you are right! It is related to pixman. I updated it and now it is fine! 
It took conda a very long time to find pixman 0.40.0 but now everything works! Thank you.
