### ISSUE TITLE
Getting "Unsupported or missing image file" on a .mrxs picture

### ISSUE THREAD

**Issue by AlgorithmesAndCo** [openslide/openslide#453]
### Operating system

Windows 10

### Platform

64-bit

### OpenSlide version

openslide-python 1.2.0

### Slide format

MRXS

### Issue details

Hello,

We are using openslide to open MRXS pictures, and it is working very well, ...

Except, we just received a set of pictures that don't seem to work! The message is the following:
**Unsupported or missing image file**

Stack logs:
[...]
  File "D:\Ludo\git\morehistoClassic\build\lib\bioimg\io\image.py", line 992, in __init__
    img = openslide.OpenSlide(f)
  File "C:\Users\Tristan\AppData\Roaming\Python\Python37\site-packages\openslide\__init__.py", line 166, in __init__
    self._osr = lowlevel.open(str(filename))
  File "C:\Users\Tristan\AppData\Roaming\Python\Python37\site-packages\openslide\lowlevel.py", line 195, in _check_open
    raise OpenSlideUnsupportedFormatError("Unsupported or missing image file")
openslide.lowlevel.OpenSlideUnsupportedFormatError: Unsupported or missing image file

Of course I checked that the file was present and that the filename was 100% correct!

I was able to open the pictures in ImageJ (at lowest resolution, of course)

I can provide one of these pictures, but they're fairly big, and I don't want to the link to be public, if you don't mind...

I hope you'll be able to help us... 

Thanks in advance

**Comment by bgilbert** [comment]
Could you set the `OPENSLIDE_DEBUG` environment variable to `detection`, try to load the slide, and post the output?

Also, what build of the OpenSlide binaries are you using?

You can upload a sample slide [here](https://docs.google.com/forms/d/e/1FAIpQLSf4RsqIEVqB_FlY0mJtmi9fhHNSqc_59e4uHIoAgtkbtplH0w/viewform).  If you select "Share this slide only with OpenSlide maintainers", only the maintainers will have access to it.

**Comment by AlgorithmesAndCo** [comment]
Hello Gilbert,

I uploaded one of my faulty files, added an env. var. OPENSLIDE_DEBUG=detection, but I can't see any additional debug, I get an exception as soon as the file is opened.

For the exact version of openslide-python I'm using, please find attached a text file containing the result of "pip debug --verbose openslide-python". I guess that should be what you want, but feel free to come back to me for even more details.

Regards,

Ludo

[openslide-install-details.txt](https://github.com/openslide/openslide/files/11650239/openslide-install-details.txt)

**Comment by bgilbert** [comment]
> I uploaded one of my faulty files, added an env. var. OPENSLIDE_DEBUG=detection, but I can't see any additional debug, I get an exception as soon as the file is opened.

You'd need to set that environment variable before doing `import openslide`.  I'll take a look at your sample.

> For the exact version of openslide-python I'm using, please find attached a text file containing the result of "pip debug --verbose openslide-python". I guess that should be what you want, but feel free to come back to me for even more details.

That gives the version of OpenSlide Python, not of OpenSlide.  You previously downloaded and unpacked an openslide-win64 ZIP, right?  What is the date code on that build?

**Comment by bgilbert** [comment]
The name of the slide's data directory should be equal to the name of the `.mrxs` file without the `.mrxs` extension.  That's not true for your sample slide, so OpenSlide can't locate the slide data.  On my machine, if I rename your data directory to match the `.mrxs` file, OpenSlide is able to read the slide.
