### ISSUE TITLE
DICOM clone layers bug

### ISSUE THREAD

**Issue by CGDogan** [openslide/openslide#468]
### Operating system

macOS 13

### Platform

ARM

### OpenSlide version

head of 1 Jul 2023; commit af4878bn

### Slide format

dcm

### Issue details

We have this code:

```
  for (int32_t i = 0; i < openslide_levels; i++) {
    openslide_get_level_dimensions(osr, i, &ww, &hh);
    cout << ww << " " << hh << endl;
```

Tiff reading through openslide works for us, and this code prints:

```
ca-iip	| ww,hh:
ca-iip	| 2560 1664
ca-iip	| 1280 832
ca-iip	| 640 416
ca-iip	| 320 208
ca-iip	| 160 104
```

but when I converted it to DICOM using Google's wsi-to-dicom, I get:

```
ca-iip	| 2560 1664
ca-iip	| 2560 1664
ca-iip	| 2560 1664
ca-iip	| 1280 832
ca-iip	| 640 416
ca-iip	| 320 208
ca-iip	| 160 104
```

and this explains why we get zoomed-in tiles; openslide doesn't zoom in but clones the image and adds them to the front. But is this expected behavior? I get the same quirk for all WSI DICOM files.

img1.png is the original file

Pyvips generated from [img1.png](https://github.com/openslide/openslide/assets/126820728/7bf24736-e3ee-4d49-883c-78b910458e06), img1_png_conv.tif
[img1_png_conv.tif.zip](https://github.com/openslide/openslide/files/11926881/img1_png_conv.tif.zip) and using google's wsi-to-dicom, 
[DCM_3.dcm.zip](https://github.com/openslide/openslide/files/11926883/DCM_3.dcm.zip). And I verified that we call openslide get level functions with the same parameters and the results for the dcm and tiff can be found in these folders.
[dcm3.zip](https://github.com/openslide/openslide/files/11926885/dcm3.zip)
[tiff.zip](https://github.com/openslide/openslide/files/11926886/tiff.zip)
I see that our internal zoom measure of 11 for DeepZoom in tiff gives us the same real zoom level as 9 in dicom and I suspect that off-by-two can also be seen in the code above.

But an easier testcase to help you debug is [sm_image.dcm](https://github.com/ImagingDataCommons/libdicom/blob/main/data/test_files/sm_image.dcm) which prints:

```
ca-iip	| ww,hh:
ca-iip	| 50 50
ca-iip	| 50 50
ca-iip	| 50 50
```

CC @jcupitt, thank you for your work on DICOM

**Comment by bgilbert** [comment]
Hmm, I can't reproduce this on `sm_image.dcm` or any of the openslide-testdata slides.  I used this code:

```c
#include <stdio.h>
#include <inttypes.h>
#include <openslide.h>

int main(int argc, char **argv) {
  openslide_t *osr = openslide_open(argv[1]);
  int64_t w, h;
  for (int i = 0; i < openslide_get_level_count(osr); i++) {
    openslide_get_level_dimensions(osr, i, &w, &h);
    printf("%d %"PRId64" %"PRId64"\n", i, w, h);
  }
}
```

Could you post a standalone code sample?

**Comment by CGDogan** [comment]
Extremely sorry, I wasn't aware that the OpenSlide library kept an internal state, this explains it, where I ran your code:

```
# ./a.out posdebug.dcm
0 160 104
# ./a.out posdebug4.dcm
0 2560 1664
1 160 104
# ./a.out posdebug.dcm
0 2560 1664
1 160 104
```

**Comment by CGDogan** [comment]
Sorry @bgilbert , is this expected behavior? I'm not familiar at all with how OpenSlide handles WSI split among files.

```
#include <stdio.h>
#include <inttypes.h>
#include <openslide.h>

int main(int argc, char **argv) {
  openslide_t *osrT = openslide_open(argv[1]);
  openslide_t *osr = openslide_open(argv[2]);
  openslide_close(osrT);

  int64_t w, h;
  for (int i = 0; i < openslide_get_level_count(osr); i++) {
    openslide_get_level_dimensions(osr, i, &w, &h);
    printf("%d %"PRId64" %"PRId64"\n", i, w, h);
  }
}
```
prints:
```
0 2560 1664
1 2560 1664
2 160 104
3 160 104
```

**Comment by CGDogan** [comment]
@bgilbert I found the cause, but I'm not sure if this is a bug or a feature (something an OpenSlide lib user needs to handle), please inform me about whether this is the correct behavior and we should handle this or this will be changed before the release.

When we have `testsmall.dcm` and `testbig.dcm`, and when we `openslide_open` (at least) one of them, we have

```
0 2560 1664
1 160 104
```

So when we run openslide_open once, OpenSlide checks the directory for other dicom files and opens the other ones as well, ones that have matching unique dicom ids.

But if I clone `testsmall.dcm` to `testother.dcm` in the same directory, but not openslide_open this file, then it'll still include this file and say:

```
0 2560 1664
1 160 104
2 160 104
```

And I find this surprising that OpenSlide reads other files if we don't run openslide_open on them. Was this expected?

**Comment by jcupitt** [comment]
Hi @CGDogan, it looks like the dicom driver in openslide is not splitting a directory of DCMs into slides correctly in this case.

Could you zip up the whole directory and put it on a file sharing site somewhere? It'd help me fix the logic if I had a good test case.

**Comment by jcupitt** [comment]
It does try to only include files which form a sensible pyramid, but it's not doing that correctly in this case, so I think there's probably an improvement we could make here. 

If you have time, a sample zip would help.

**Comment by bgilbert** [comment]
@jcupitt As I understand it, the issue is that we're treating every file with the same series instance UUID as part of the same slide, even if some of the files are exact duplicates of each other.  We should at least filter out exact copies; hopefully there's another UUID we can use for that.  For robustness I wonder if we should also fail if we detect identical image sizes from non-identical files?

**Comment by CGDogan** [comment]
Thank you @jcupitt , I attached two files here https://github.com/openslide/openslide/files/11929805/testdcm.zip which you can extract to a folder. You'll see that you can openslide_open one of them and you'll have two resolutions but if you duplicate one of the dicoms and then do openslide open, you'll have a duplicate layer

**Comment by jcupitt** [comment]
@bgilbert exactly, I'll try to improve the filtering. It has some filtering, it's just obviously not quite enough in this case.

**Comment by jcupitt** [comment]
Ah, I understand now, thanks for test testcase @CGDogan. I agree it's not really a bug, but this will probably happen rather often, so it's probably sensible for openslide to detect and avoid it.

I've made a PR: https://github.com/openslide/openslide/pull/470

This is happening in the most obvious way. For example:

```shell
$ unzip ../testdcm.zip
$ ls
testbig.dcm  testsmall.dcm
$ vipsheader -a testbig.dcm 
...
openslide.level-count: 2
openslide.level[0].downsample: 1
openslide.level[0].height: 1664
openslide.level[0].tile-height: 500
openslide.level[0].tile-width: 500
openslide.level[0].width: 2560
openslide.level[1].downsample: 16
openslide.level[1].height: 104
openslide.level[1].tile-height: 500
openslide.level[1].tile-width: 500
openslide.level[1].width: 160
...
```

So a two-level pyramid. Now copy one of the files:

```shell
$ cp testsmall.dcm testsmall2.dcm 
$ ls
testbig.dcm  testsmall2.dcm  testsmall.dcm
$ vipsheader -a testbig.dcm 
...
openslide.level-count: 3
openslide.level[0].downsample: 1
openslide.level[0].height: 1664
openslide.level[0].tile-height: 500
openslide.level[0].tile-width: 500
openslide.level[0].width: 2560
openslide.level[1].downsample: 16
openslide.level[1].height: 104
openslide.level[1].tile-height: 500
openslide.level[1].tile-width: 500
openslide.level[1].width: 160
openslide.level[2].downsample: 16
openslide.level[2].height: 104
openslide.level[2].tile-height: 500
openslide.level[2].tile-width: 500
openslide.level[2].width: 160
...
```

So the extra level has all the correct UIDs etc, it's simply a file copy of an existing level. The PR filters duplicate levels during `dicom_open()`, so it fixes this.

Duplicate associated images are already removed by the hash table.

**Comment by jcupitt** [comment]
> I find this surprising that OpenSlide reads other files if we don't run openslide_open on them. Was this expected?

Yes, the design of DICOM forces this. A directory can contain several slides, and a slide can span many files.

When you open `some/path/a.dcm`, openslide extracts the slide UID, then scans `some/path` for all files with a matching UID. It assembles those files into a pyramid plus associated label, thumbnail and macro. This means you can run openslide on any of the files that make up a slide (you don't need to scan the directory yourself to work out which files it's made of), and openslide can also keep the set of slides in a directory separate.

**Comment by CGDogan** [comment]
@jcupitt Thank you for the investigation, that explains it well!
