### ISSUE TITLE
Visible tile borders after recent ICC updates

### ISSUE THREAD

**Issue by jetic83** [openslide/openslide#483]
### Operating system

Windows Server 2019

### Platform

64-bit

### OpenSlide version

Winbuild ce8bd563

### Slide format

SVS, TIFF

### Issue details

When using the new OS version (since nightly Win 64 build ...), we see the tile borders in the viewer.

We use tile size of 512, overlap 1. This also remains with larger or smaller overlaps. The point is, with same settings, and old OS build, we do not see any tile borders.

This affects svs, tiff files (possibly even more). See screenshots.

Was there a change in how tiles are extracted from the files?

![image](https://github.com/openslide/openslide/assets/11157551/6cf6b192-fd8e-43dc-b7ba-1e1bb405e0fe)
This is with release version 2023-04-14 Win 64 bit

![image](https://github.com/openslide/openslide/assets/11157551/bc67002a-f701-4cbd-b203-cdc689e1c942)
This is with Winbuild ce8bd563 (2023-07-21) and ce8bd563 (2023-07-23)

**Comment by bgilbert** [comment]
Thanks for the report.  What viewer are you using?  ICC profile support is relevant if you're using the latest version of the OpenSlide Python example viewers, or if your viewer is actively reading and applying ICC profiles, but shouldn't affect older viewer code.

Possible causes are #413 and #447.  Could you test the [nightly builds](https://openslide.org/builds/windows/) from May 13 and May 14?

**Comment by bgilbert** [comment]
Okay, I was able to reproduce this with the Java viewer, both on Windows and Linux.  May 13 is okay but May 14 isn't, so the cause was #447.
