### ISSUE TITLE
Does Opensilde cache slide data in RAM or Harddisk?

### ISSUE THREAD

**Issue by orange119120** [openslide/openslide#495]
### Issue details

# Context:
In our lab, we have built an inference pipeline using openslide to access image pixel data
We have noticed significant overhead in I/O of slide pixels (30%-40%) of our prediction step, so we are looking for opportunities to minimize the time required to process one slide. Our slides are typically 1-5GB big and our workstations have 64-128GB RAM that should be able to handle the slides.

# Question:
Does openslide cache all pixel data in RAM, or does it access it from disk?
If it is on disk, does that mean using an HDD, SSD, or SSD (m.2) will have a significant impact on performance?

**Comment by bgilbert** [comment]
OpenSlide caches decompressed pixel data in RAM, and your operating system should also cache disk blocks in RAM.  OpenSlide's cache is 32 MiB per `openslide_t` by default, but can be changed in the upcoming OpenSlide 4.0.0 (or current Git master) using the [cache API](https://github.com/openslide/openslide/blob/239d7bd9f603be159e6558464f311b5b243d12b1/src/openslide.h#L547-L589).

**Comment by tourist-C** [comment]
Thank you, I will keep an eye on the upcoming 4.0.0 release
