### ISSUE TITLE
FAILED: src/openslide-1.dll.p/openslide-decode-gdkpixbuf.c.obj Error message: There are syntax errors and undeclared identifiers.

### ISSUE THREAD

**Issue by HarshadHapaniWork** [openslide/openslide#536]
### Operating system

window 11

### Platform

64bit

### OpenSlide version

4.0

### Slide format

svs

### Issue details

I'm trying to build the OpenSlide project on Windows using Visual Studio, following the recommended setup steps, but I encountered an error during the compilation process.

**Steps to Reproduce:**
1. Download OpenSlide project from the repository.
2. Install the necessary toolchain for Windows in Visual Studio.
3. Install Meson for Windows.
4. Install all necessary libraries using the `pacman` command.
5. No changes were made to the code.
6. Run `meson setup builddir` successfully.
7. Run `meson compile -C builddir` which resulted in the error.

**Error:**
FAILED: src/openslide-1.dll.p/openslide-decode-gdkpixbuf.c.obj
Error message: There are syntax errors and undeclared identifiers.
Build stopped: subcommand failed.

**Comment by bgilbert** [comment]
OpenSlide can't be built with MSVC, since it uses GCC extensions (notably the [cleanup attribute](https://gcc.gnu.org/onlinedocs/gcc/Common-Variable-Attributes.html#index-cleanup-variable-attribute), which is pervasively used throughout the codebase).  Clang should work though.

OpenSlide's Meson config should have caught this, though.  Could you post the log from `meson setup`?

**Comment by HarshadHapaniWork** [comment]
here log form meson setup 

> 

> PS D:\PathPresenter\Openslide\openslide-main> meson setup builddir --wipe
The Meson build system
Version: 1.2.3
Source dir: D:\PathPresenter\Openslide\openslide-main
Build dir: D:\PathPresenter\Openslide\openslide-main\builddir
Build type: native build
Project name: openslide
Project version: 4.0.0
C compiler for the host machine: cl (msvc 19.29.30152 "Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30152 for x86")
C linker for the host machine: link link 14.29.30152.0
Host machine cpu family: x86
Host machine cpu: x86
Compiler for C supports arguments -Wstrict-prototypes: NO
Compiler for C supports arguments -Wmissing-prototypes: NO
Compiler for C supports arguments -Wmissing-declarations: NO
Compiler for C supports arguments -Wnested-externs: NO
Compiler for C supports arguments -fno-common: NO
Compiler for C supports link arguments -Wl,--no-undefined: NO
Message: Using "N" flag for close-on-exec (Windows)
cl.exe does not actually support gnu standards, and meson will instead demote to the nearest ISO C standard. This may cause compilation to fail.
Checking for function "floor" : YES
Checking for function "floor" : YES (cached)
Found pkg-config: C:\msys64\mingw64\bin\pkg-config.EXE (0.29.2)
Run-time dependency zlib found: YES 1.3
Run-time dependency libjpeg found: YES 3.0.1
Run-time dependency libpng found: YES 1.6.40
Run-time dependency libopenjp2 found: YES 2.5.0
Run-time dependency libtiff-4 found: YES 4.6.0
Run-time dependency glib-2.0 found: YES 2.78.1
Run-time dependency gio-2.0 found: YES 2.78.1
Run-time dependency gobject-2.0 found: YES 2.78.1
Run-time dependency cairo found: YES 1.18.0
Run-time dependency gdk-pixbuf-2.0 found: YES 2.42.10
Run-time dependency libxml-2.0 found: YES 2.11.5
Run-time dependency sqlite3 found: YES 3.44.0
Found CMake: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.EXE (3.20.21032501)
Run-time dependency libdicom found: NO (tried pkgconfig and cmake)
Looking for a fallback subproject for the dependency libdicom

Executing subproject libdicom

libdicom| Project name: libdicom
libdicom| Project version: 1.0.5
libdicom| C compiler for the host machine: cl (msvc 19.29.30152 "Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30152 for x86")
libdicom| C linker for the host machine: link link 14.29.30152.0
libdicom| Check usable header "utarray.h" : NO
libdicom| Run-time dependency uthash found: NO (tried pkgconfig and cmake)
libdicom| Looking for a fallback subproject for the dependency uthash

Executing subproject libdicom:uthash

uthash| Project name: uthash
uthash| Project version: 2.3.0
uthash| C compiler for the host machine: cl (msvc 19.29.30152 "Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30152 for x86")
uthash| C linker for the host machine: link link 14.29.30152.0
uthash| Build targets in project: 0
uthash| Subproject uthash finished.

libdicom| Dependency uthash from subproject subprojects/uthash-2.3.0 found: YES 2.3.0
libdicom| Has header "io.h" : YES
libdicom| Has header "unistd.h" : NO
libdicom| Compiler for C supports function attribute constructor: NO
libdicom| Configuring config.h using configuration
libdicom| Compiler for C supports arguments -Wformat-security: NO
libdicom| Compiler for C supports arguments -Wmissing-declarations: NO (cached)
libdicom| Compiler for C supports arguments -Wmissing-prototypes: NO (cached)
libdicom| Compiler for C supports arguments -Wnested-externs: NO (cached)
libdicom| Compiler for C supports arguments -Wstrict-prototypes: NO (cached)
libdicom| Configuring version.h using configuration
libdicom| Configuring dcm-dump.1 using configuration
libdicom| Configuring dcm-getframe.1 using configuration
libdicom| Build targets in project: 5
libdicom| Subproject libdicom finished.

Dependency libdicom found: YES 1.0.5 (overridden)
Run-time dependency valgrind found: NO (tried pkgconfig)
Program doxygen found: NO
Header "glib.h" has symbol "G_DEFINE_AUTOPTR_CLEANUP_FUNC" with dependency glib-2.0: YES
Message: Configuring tests with 4-byte stack alignment
Compiler for C supports arguments -mpreferred-stack-boundary=2: NO
Configuring config.h using configuration
Configuring openslide-dll.manifest using configuration
Configuring openslide-dll.rc using configuration
Windows resource compiler: Microsoft (R) Windows (R) Resource Compiler Version 10.0.10011.16384
Configuring openslide-quickhash1sum.1 using configuration
Configuring openslide-show-properties.1 using configuration
Configuring openslide-write-png.1 using configuration
Configuring slidetool.1 using configuration
Configuring driver using configuration
Build targets in project: 21

openslide 4.0.0

  Subprojects
    libdicom: YES
    uthash  : YES (from libdicom)

Found ninja-1.11.1 at "C:\Program Files\Meson\ninja.EXE"

**Comment by bgilbert** [comment]
Ah, okay, it's a detection bug.  In `meson.build`, could you try replacing `G_DEFINE_AUTOPTR_CLEANUP_FUNC` with `g_autofree` and confirm that `meson setup` fails now?

**Comment by HarshadHapaniWork** [comment]
yes its fails now..
![image](https://github.com/openslide/openslide/assets/123565938/ff6e582c-2937-4765-b63f-a10961c80d67)

then how to setup and compile, please provide steps

**Comment by bgilbert** [comment]
Great, thanks for checking!

Visual Studio [also supports Clang](https://learn.microsoft.com/en-us/cpp/build/clang-support-msbuild?view=msvc-170).  I haven't tried building OpenSlide that way, but I think it should work.  If it doesn't, please open a bug.

Alternatively, we provide [OpenSlide binaries for Windows](https://openslide.org/download/#binaries) with all OpenSlide dependencies built into a single DLL.

Thanks for reporting this!

**Comment by HarshadHapaniWork** [comment]
Could you provide your way/steps to compile and build OpenSlide.

**Comment by bgilbert** [comment]
The code we use to build OpenSlide and its dependencies for Windows is in [this repository](https://github.com/openslide/openslide-bin/).  That code is rapidly changing right now, and the correct way to run it will change soon, but the README will be kept up to date.

**Comment by HarshadHapaniWork** [comment]
After transitioning from the "Microsoft (R) C/C++ Optimizing Compiler" to GCC, 
The openslide project now compiles successfully.

@bgilbert  Thanks for your immediate and instant support.
