### ISSUE TITLE
Cannot read raw tile

### ISSUE THREAD

**Issue by eokoshi** [openslide/openslide#546]
### Operating system

Windows 10, WSL2 Ubuntu 22.04

### Platform

AMD 64-bit

### OpenSlide version

3.4.1+dfsg-5build1

### Slide format

.tiff

### Issue details

I read in WSI using open_slide() but when I try to use slide.read_region -- I get a "Cannot read raw tile" error message. 
I have tried many different slides and I get the same result. 
However, sometimes it can read the file no problem at higher levels. I am trying to read in my slides at level 6. Anything lower than level 6 is no good, but higher can sometimes work. When I input the "size" parameter into the read_region function, it will give me this error message unless the size is under y=512 for some slides. 
I have not been able to find any mention of this error elsewhere online.

**Comment by bgilbert** [comment]
One possible cause is that tiles are missing from the TIFF.  That shouldn't happen with standards-conforming TIFF files, but isn't too surprising with whole-slide image formats that happen to use TIFF as a container.  How did you produce these files?  Are they output from a particular model of slide scanner?

**Comment by eokoshi** [comment]
Thank you for your prompt response.

They are .tiff files generated from Philips .isyntax files using the Philips Pathology SDK.
They are able to be opened using the ASAP software, albeit often with large black areas. 

I am trying to open these .tiff files and downsample them so that they can be used to train a segmentation model. 
If I try to open them normally, I get a "Unable to write to memory" error, so I am trying to open them at level 6, which would suit my purposes well. 
I apologize for the basic-level question, and appreciate your help.

**Comment by bgilbert** [comment]
Ah, okay.  That format is probably what OpenSlide calls "Philips TIFF", and OpenSlide should be able to read it correctly, including the missing tiles.  To debug this, I'll need a couple pieces of information:

- The output of running `openslide-show-properties` on an affected slide.
- The output of running `tiffinfo -s` on the same slide.

You can upload those here, or email them to the address in my GitHub profile.  The second one, especially, will be large.  Feel free to redact any identifying information from the output.

You could also try with OpenSlide 4.0.0, which has had many changes since 3.4.1, but I don't think any of those immediately explain what you're seeing.

Thanks for reporting this!

**Comment by eokoshi** [comment]
Here is the code and error message. 
When I input a tuple for the `size` parameter, it somtimes works for y values under 512, i.e. `size = (3000,512)` but will break for `size = (3000,513)`
Also, strangely, it appears to work fine with lower AND higher levels sometimes, i.e. 
`size = slide.level_dimensions[6]` 
`level=5` and `level=7` is OK but `level=6` is no good

```python
from openslide import open_slide

slide = open_slide("data/input_wsi_xml/anon___077X1000331697S0031_PD-L1_22C3_Neg_20230210_174455.tiff")
region = slide.read_region(location=(0,0),
                           level=6,
                           size=slide.level_dimensions[6])
```
```python
---------------------------------------------------------------------------
OpenSlideError                            Traceback (most recent call last)
/home/pathology/ethancoding/PDL1/PD-L1_Scoring_Model/PDL1_playground.ipynb Cell 31 line 4
      1 from openslide import open_slide
      3 slide = open_slide("data/input_wsi_xml/anon___077X1000331697S0031_PD-L1_22C3_Neg_20230210_174455.tiff")
----> 4 region = slide.read_region(location=(0,0),
      5                            level=6,
      6                            size=slide.level_dimensions[6])

File ~/ethancoding/PDL1/.venv/lib/python3.10/site-packages/openslide/__init__.py:251, in OpenSlide.read_region(self, location, level, size)
    241 def read_region(self, location, level, size):
    242     """Return a PIL.Image containing the contents of the region.
    243 
    244     location: (x, y) tuple giving the top left pixel in the level 0
   (...)
    249     Unlike in the C interface, the image data returned by this
    250     function is not premultiplied."""
--> 251     region = lowlevel.read_region(
    252         self._osr, location[0], location[1], level, size[0], size[1]
    253     )
    254     if self._profile is not None:
    255         region.info['icc_profile'] = self._profile

File ~/ethancoding/PDL1/.venv/lib/python3.10/site-packages/openslide/lowlevel.py:335, in read_region(slide, x, y, level, w, h)
    333     return Image.new('RGBA', (w, h))
    334 buf = (w * h * c_uint32)()
--> 335 _read_region(slide, buf, x, y, level, w, h)
    336 return _load_image(buf, (w, h))

File ~/ethancoding/PDL1/.venv/lib/python3.10/site-packages/openslide/lowlevel.py:233, in _check_error(result, func, args)
    231 err = get_error(args[0])
    232 if err is not None:
--> 233     raise OpenSlideError(err)
    234 return _check_string(result, func, args)

OpenSlideError: Cannot read raw tile
```


My apologies, I am using openslide in python, so I am not sure how to generate the outputs using those two functions you mentioned. Is there a way I can call them in python?
In case it is helpful, here is the `.properties` attribute of the slide
```
<_PropertyMap {'openslide.level-count': '10', 'openslide.level[0].downsample': '1', 'openslide.level[0].height': '90624', 'openslide.level[0].tile-height': '512', 'openslide.level[0].tile-width': '512', 'openslide.level[0].width': '201216', 'openslide.level[1].downsample': '2', 'openslide.level[1].height': '45312', 'openslide.level[1].tile-height': '512', 'openslide.level[1].tile-width': '512', 'openslide.level[1].width': '100608', 'openslide.level[2].downsample': '4', 'openslide.level[2].height': '22656', 'openslide.level[2].tile-height': '512', 'openslide.level[2].tile-width': '512', 'openslide.level[2].width': '50304', 'openslide.level[3].downsample': '8', 'openslide.level[3].height': '11328', 'openslide.level[3].tile-height': '512', 'openslide.level[3].tile-width': '512', 'openslide.level[3].width': '25152', 'openslide.level[4].downsample': '16', 'openslide.level[4].height': '5664', 'openslide.level[4].tile-height': '512', 'openslide.level[4].tile-width': '512', 'openslide.level[4].width': '12576', 'openslide.level[5].downsample': '32', 'openslide.level[5].height': '2832', 'openslide.level[5].tile-height': '512', 'openslide.level[5].tile-width': '512', 'openslide.level[5].width': '6288', 'openslide.level[6].downsample': '64', 'openslide.level[6].height': '1416', 'openslide.level[6].tile-height': '512', 'openslide.level[6].tile-width': '512', 'openslide.level[6].width': '3144', 'openslide.level[7].downsample': '128', 'openslide.level[7].height': '708', 'openslide.level[7].tile-height': '512', 'openslide.level[7].tile-width': '512', 'openslide.level[7].width': '1572', 'openslide.level[8].downsample': '256', 'openslide.level[8].height': '354', 'openslide.level[8].tile-height': '512', 'openslide.level[8].tile-width': '512', 'openslide.level[8].width': '786', 'openslide.level[9].downsample': '512', 'openslide.level[9].height': '177', 'openslide.level[9].tile-height': '512', 'openslide.level[9].tile-width': '512', 'openslide.level[9].width': '393', 'openslide.quickhash-1': 'c9e31aa8d70e9bd1a2ad20e37b286c59801426ebfd016334766cababe460acf1', 'openslide.vendor': 'generic-tiff', 'tiff.ResolutionUnit': 'inch'}>
```

**Comment by bgilbert** [comment]
Yup, that's all consistent with unexpected missing tiles.  The property map is equivalent to the `openslide-show-properties` output, and shows that OpenSlide is detecting the file as a standards-conforming TIFF rather than Philips.  I'll need the `tiffinfo` output (or a sample slide file) to figure out why.  You can run that command from the WSL command-line after installing the `libtiff-tools` package into WSL.  Alternatively, if you're able to upload an entire sample file, you can do that [here](https://openslide.org/submit/).

**Comment by eokoshi** [comment]
I have submitted a slide to the website. 
Here is the tiffinfo output as well. 

[tiffoutput.txt](https://github.com/openslide/openslide/files/13483433/tiffoutput.txt)

**Comment by bgilbert** [comment]
Thank you!  From the dump it appears that your slide isn't actually a "Philips TIFF", but may actually be a correct TIFF that just has missing tiles.  That means the generic TIFF driver will need to support those.  It shouldn't be a big change, but it'll require some code.

It is technically possible to modify the slide file to add surrogate tiles, but it's probably not worth the effort.  I'd suggest waiting for a fix.  I'll try to get a pull request posted soon, and will CC you so you can test the changes.  To do that, you'll need to be able to compile OpenSlide from source code.

Thanks again for reporting this.  OpenSlide improves as a direct result of reports like yours.

**Comment by bgilbert** [comment]
https://github.com/openslide/openslide/pull/547 should fix the problem, and allows me to read the slide you submitted.  Are you able to try it out?

**Comment by eokoshi** [comment]
I apologize for the novice question, but where do I access the updated source code to test this out? I would have to compile using meson, right? 
Would I simply put the openslide files in the directory with the other programs (/usr/bin ?) and then run the meson setup builddir function?

My apologies again. Your help is greatly appreciated.

**Comment by bgilbert** [comment]
No apologies necessary; the build procedure isn't necessarily obvious.  You'd need to compile with Meson, yes.  At a WSL bash prompt, you can do something like:

```console
# update package index
apt update
# install build dependencies
apt install git gcc meson pkg-config zlib1g-dev libpng-dev libjpeg-turbo8-dev \
    libtiff-dev libopenjp2-7-dev libgdk-pixbuf2.0-dev libxml2-dev libsqlite3-dev \
    libcairo2-dev libglib2.0-dev
# change to your home directory (any convenient directory will work)
cd ~
# fetch pull request branch
git clone https://github.com/bgilbert/openslide -b sparse-generic-tiff
# build and install
cd openslide
meson setup builddir
meson compile -C builddir
meson install -C builddir
```

This will install into `/usr/local`, which should automatically be searched before your existing installation in `/usr`.

Note that OpenSlide Python older than 1.3.0 won't work with OpenSlide 4.0.0+.  If you installed OpenSlide Python from the Ubuntu `python3-openslide` package, you'll need to upgrade with `apt install python3-pip; pip install openslide-python`.

**Comment by bgilbert** [comment]
Ah, for the last command you'll need `sudo meson install -C builddir`.

**Comment by eokoshi** [comment]
Looks like it is able to read the images with missing tiles!

![image](https://github.com/openslide/openslide/assets/127910259/e449d5f5-26c4-4ea6-9d85-f71b4e63bcc8)

Thank you so much for your prompt replies.

**Comment by bgilbert** [comment]
Great!  Thanks for reporting this!
