### ISSUE TITLE
Issue with MRXS File Handling in OpenSlide 1.3.1 on Ubuntu 18.04.6 LTS: need help

### ISSUE THREAD

**Issue by HaozhongMa** [openslide/openslide#559]
### Operating system

Linux

### Platform

Ubuntu 18.04.6 LTS

### OpenSlide version

1.3.1

### Slide format

mrxs

### Issue details

Hi,

I hope this message finds you well. I am writing to report an issue I've encountered while using OpenSlide version 1.3.1 on an Ubuntu 18.04.6 LTS system with Python 3.8.

I have been successfully using OpenSlide for handling .svs files, and it has been functioning impeccably in this regard. However, I recently faced a significant problem when working with .mrxs files. The issue is as follows:

Problem Description: Every .mrxs file is being incorrectly recognized as having the same dimensions, regardless of their actual size.
![image](https://github.com/openslide/openslide/assets/66115097/4c961151-033d-40a3-a34c-71c732c3dcc1)

Resulting Error: When attempting to view these .mrxs files, OpenSlide generates an all-black image, which suggests a problem in the file reading or rendering process.

This issue is critical for my work as it hinders the analysis of .mrxs files, which are essential in my current projects.

I would greatly appreciate any guidance or suggestions you might have to resolve this issue. If there are any further details or specific diagnostic information you require, please do not hesitate to let me know.

Thank you for your time and assistance. I look forward to your valuable insights on this matter.

Best regards,
Haozhong Ma

**Comment by bgilbert** [comment]
OpenSlide uses the coordinate plane of the MRXS file, which covers the entire scan area.  The portions that do not have image data are rendered as transparent pixels, which will appear black if you ignore transparency data.  Use the alpha channel of region images to distinguish between transparent pixels, opaque pixels with valid image data, and partially transparent pixels (which can occur at boundaries between opaque and transparent areas at some zoom levels).

For convenience, OpenSlide provides properties that give the bounding box of the slide region containing valid image data.  See the `openslide.bounds-*` [property documentation](https://openslide.org/docs/properties/) for more information.
