### ISSUE TITLE
Opening ndpi files > 4 Gb

### ISSUE THREAD

**Issue by cpath-ukk** [openslide/openslide#560]
### Operating system

Ubuntu 22.04

### Platform

64-bit x86

### OpenSlide version

4.0.0

### Slide format

NDPI

### Issue details

Dear developers,

in the previous version of openslide there was a problem with opening the ndpi slides > 4 Gb.

I installed a new version of the openslide 4.0.0 with openslide-python 1.3.1 (tried apt and conda based installation), but the problem still persists:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/openslide/__init__.py", line 463, in open_slide
    return OpenSlide(filename)
  File "/usr/lib/python3/dist-packages/openslide/__init__.py", line 179, in __init__
    self._osr = lowlevel.open(str(filename))
  File "/usr/lib/python3/dist-packages/openslide/lowlevel.py", line 207, in _check_open
    raise OpenSlideError(err)
openslide.lowlevel.OpenSlideError: Can't validate JPEG for directory 0: Expected marker at 4294969074, found none

Are there any possibilities to work around here? Was the problem not corrected in the 4.0.0 update?

Thank you in advance

**Comment by bgilbert** [comment]
OpenSlide does not yet have support for large NDPI files.  This issue is tracked in #174.

Closing as duplicate.  Thanks for the report.
