### ISSUE TITLE
Debian package

### ISSUE THREAD

**Issue by AzHicham** [openslide/openslide#563]
### Issue details

Hello, 

Is it possible to provide debian package for openslide 4.0.0 ? 
Or at least provide instruction in order to build libopenslide1 & libopenslide-dev ? 

Right now I was able to package libopenslide1 using the following commands: 
```bash
git checkout tags/v4.0.0 && \
meson setup builddir /opt/openslide/ && \
USER=root dh_make --createorig -p openslide_4.0.0 -y -s && \
dh_auto_configure --buildsystem=meson && \
dpkg-buildpackage -rfakeroot -us -uc -b 
```
Then when I run 
`gdebi openslide_4.0.0.deb` all Runtime dependencies will be installed.

But I had some trouble to build a libopenslide-dev package. I need this one in order to be able to install automatically -dev packages of following libraries : glib2.0, libxml2, etc ...
Because when I run the command: 
`PKG_CONFIG_ALLOW_SYSTEM_LIBS=1 PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1 pkg-config --libs --cflags openslide`
I have the following error :
```
Package glib-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `glib-2.0.pc'
to the PKG_CONFIG_PATH environment variable
Package 'glib-2.0', required by 'openslide', not found
```
Indeed glib-2.0 is installed but not .pc file can be found by pkg-config since glib-2.0-dev was not installed.

Thanks you :)

**Comment by bgilbert** [comment]
While we do provide a [Fedora Copr](https://copr.fedorainfracloud.org/coprs/g/openslide/openslide/) and an [Ubuntu PPA](https://launchpad.net/~openslide/+archive/ubuntu/openslide) with OpenSlide packages, we generally rely on downstream packagers to package OpenSlide releases for their distros.  The [Debian Med](https://www.debian.org/devel/debian-med/) team maintains Debian's OpenSlide package; please feel free to follow up with them about updating it to 4.0.0.

If you want to do your own package build, the source package from the PPA might be a good starting point.

**Comment by AzHicham** [comment]
Thanks I'll try to contact them

**Comment by bgilbert** [comment]
It's under the tiny "View package details" [link](https://launchpad.net/~openslide/+archive/ubuntu/openslide/+packages).  I'd start from the `mantic` build, so the source package is the last three files in the "Package files" section under "openslide - 4.0.0-0.mantic".

**Comment by AzHicham** [comment]
Thanks a lot
