### ISSUE TITLE
OSError: libopenslide.so.0

### ISSUE THREAD

**Issue by ThaoCao** [openslide/openslide#575]
### Operating system

Linux 

### Platform

64-bit 32GB GPU 

### OpenSlide version

1.3.1

### Slide format

TIF

### Issue details

I ran into the error below:
OSError: libopenslide.so.0: cannot open shared object file: No such file or directory

The error was from the lowlevel.py script:
    else:
        return try_load(['libopenslide.so.1', 'libopenslide.so.0'])
_lib = _load_library()

I think it is due to the recent breaking API change and wonder what fixes need to be done. What was the previous soname so I can check and replace. Thank you.

**Comment by bgilbert** [comment]
`libopenslide.so.0` _is_ the previous soname.  OpenSlide Python 1.3.1 tries both sonames, though the exception message only shows the last one it tried.  Is the OpenSlide library installed and in your library search path?

**Comment by ThaoCao** [comment]
thank you for clarifying! i just moved the openslide folder to the same directory as openslide_python and it worked now! Thanks!

**Comment by bgilbert** [comment]
Great, glad you got it working!
