### ISSUE TITLE
Missing ICC profile for Aperio thumbnail

### ISSUE THREAD

**Issue by 4pygmalion** [openslide/openslide#637]
### Operating system

ubuntu 20.04

### Platform

64bit x86

### OpenSlide Python version

openslide.__version__

### OpenSlide version

4.0.0

### Slide format

svs

### Describtion
I'm encountering a color mismatch between the thumbnail and slide view when working with a Leica-scanned SVS file using the `examples/deepzoom/deepzoom_server.py` example from the OpenSlide Python repository. Specifically, the colors of the tiles generated using openslide.deepzoom.DeepZoomGenerator are close to the thumbnail, but differ from what is shown in the slide view of the web viewer. The colors in the slide view appear to be adjusted or corrected in some way.

is there any color normalization applied in the web viewer's slide view? 

### Steps to Reproduce:
Load a Leica SVS file using the deepzoom_server.py script.
Compare the thumbnail with the slide view in the web viewer.

### Expected Behavior:
The colors of the thumbnail and slide view should match.

### Actual Behavior:
There is a noticeable difference between the colors in the thumbnail and the slide view. The tiles generated by DeepZoomGenerator are closer to the thumbnail colors.

![image (1)](https://github.com/user-attachments/assets/4768853b-8b2f-42bb-8969-a74a3927156d)
![image (2)](https://github.com/user-attachments/assets/3f25f6de-9c04-4a46-ba9f-885dc873d26e)

**Comment by 4pygmalion** [comment]
Thank you, @bgilbert . Your detailed explanation was really helpful. I realized I didn’t fully understand the role of ICC Profiles. It seems necessary to apply the ICC Profile from the main image to the thumbnail as well, to ensure consistency, as deepzoom_server.py stores the profile for the main image but not for the thumbnail.

**Comment by bgilbert** [comment]
Please try the latest [nightly build](https://openslide.org/builds/) and let me know whether it fixes the problem for you.  After unpacking the Linux tar archive, set the `LD_LIBRARY_PATH` environment variable to the path to the unpacked `lib` directory, then run `deepzoom_server.py`.
