### ISSUE TITLE
Publish debian package for debian trixie 

### ISSUE THREAD

**Issue by AzHicham** [openslide/openslide#645]
### Issue details

Hello, 

I now this is too late for debian bookworm, but is it possible to publish openslide 4 for debian trixie ? (at least arm64 & amd64) ? 

Thanks

**Comment by bgilbert** [comment]
Debian's OpenSlide package is maintained by the Debian Med packaging team, not the OpenSlide developers.  You could try asking the Debian Med developers.  It would indeed be useful to have the Debian package up-to-date.

**Comment by bgilbert** [comment]
Filed a [request](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1099727) in the Debian bug tracker.

**Comment by AzHicham** [comment]
Thanks I sent an email but no response so far
